### ISSUE TITLE
No way to make arg list unlimited?

### ISSUE THREAD

**Issue by trusktr** [pelotom/runtypes#1]
I see https://github.com/pelotom/runtypes/blob/master/src/index.ts#L611-L636

So it looks like there's a limit to the arg list. Is there no other way?

**Comment by pelotom** [comment]
Not in a type safe way, until TypeScript supports [variadic function types](https://github.com/Microsoft/TypeScript/issues/5453). But we can always add more overloads to that definition if you find you need more :)

**Comment by pelotom** [comment]
I should say, rather, that I don't know of a way to do it currently. Would welcome any ideas!

**Comment by gcanti** [comment]
> So it looks like there's a limit to the arg list

Theoretically unions and intersections are (commutative and) **associative**, so 2 args should be enough

```
union(A, B, C) = union(union(A, B), C) = union(A, union(B, C))

intersection(A, B, C) = intersection(intersection(A, B), C) = intersection(A, intersection(B, C))
```

For example if you have 16 args you can handle a union of 64 types with just 7 unions.

Of course, having more args is handy though.

**Comment by pelotom** [comment]
Closing this for now... will revisit once the type system allows us to do better.

**Comment by thehappycoder** [comment]
Is there any alternatives? I can't use this library because I have much more than 10 arguments to pass to `Union` function

**Comment by pelotom** [comment]
We can always add more overloads to support as many arguments as we like! Feel free to submit a PR, you just need to add more overloads [here](https://github.com/pelotom/runtypes/blob/7c71b00f1dd10f33365769250b285b9ca11c6a3e/src/types/union.ts#L126), it should be clear how to extend the existing pattern.
