### ISSUE TITLE
Make error messages at least as informative as those given by TypeScript

### ISSUE THREAD

**Issue by pelotom** [pelotom/runtypes#10]
Some examples of TypeScript's static error messages:

```ts
;(): number | boolean => 'hello'
// [ts] Type '"hello"' is not assignable to type 'number | boolean'.

;(): { x: number } => ({})
// [ts]
// Type '{}' is not assignable to type '{ x: number; }'.
//   Property 'x' is missing in type '{}'.

;(): { x: number } => ({ x: 'hello' })
// [ts]
// Type '{ x: string; }' is not assignable to type '{ x: number; }'.
//   Types of property 'x' are incompatible.
//     Type 'string' is not assignable to type 'number'.
// Record({ x: Number }).check({ x: 'hello' })

;(): { x: number } | { x: boolean } => ({ x: 'hello' })
// [ts]
// Type '{ x: "hello"; }' is not assignable to type '{ x: number; } | { x: boolean; }'.
//   Type '{ x: "hello"; }' is not assignable to type '{ x: boolean; }'.
//     Types of property 'x' are incompatible.
//       Type '"hello"' is not assignable to type 'boolean'.

;(): { x: number } | { x: boolean } => ({})
// [ts]
// Type '{}' is not assignable to type '{ x: number; } | { x: boolean; }'.
//   Type '{}' is not assignable to type '{ x: boolean; }'.
//     Property 'x' is missing in type '{}'.
```

Some notes:
- One thing we will need to do this fully is a way to infer the type of a given value (or at least a string representation of it), although this is may be more of a nice-to-have.
- We already have string representations of runtypes, via `show`
- Most type errors are flat, but records and unions can have hierarchical errors. In both cases it would be an improvement over TypeScript's static error messages if we allowed multiple sub-errors:
  - For records, multiple sub-errors represent all the fields which are missing or of the wrong type (I believe doing this correctly would address #8)
  - For unions, multiple sub-errors represent the ways in which the supplied value failed to conform to each alternative in turn. TypeScript union error messages are confusing because they show you only how it failed to match the _last_ alternative, which may well be different than the type you were attempting to match.

**Comment by spacepope** [comment]
Hi,

is there any progress on this?
That would be so great, because i am just struggling with deeply nested Records and Partials and if one property is missing on a nested Record deeper than level 3 or 4, the error message provided by check()/validate() is huge and does not really give a hint on the missing property.
(only "_Type {..} is not assignable to type {..}_" repeating over and over again; mostly the final "_Types of property '..' are incompatible_" does not point to the missing sub property at all..)

**Comment by pelotom** [comment]
No progress yet, unfortunately work has left me with little time for open source lately 😕
