### ISSUE TITLE
Lots of tests are passing by accident

### ISSUE THREAD

**Issue by davidje13** [pelotom/runtypes#102]
While looking in to #95 (trying to convert the input from `guard` to `validate`), I have observed that a large number of tests are throwing exceptions which do not relate to the intended behaviour:

```
  ● undefined › ~: Person

    RangeError: Maximum call stack size exceeded

      12 | 
      13 |   let cached: A;
    > 14 |   function getWrapped() {
         |                      ^
      15 |     if (!cached) {
      16 |       cached = delayed();
      17 |       for (const k in cached) if (k !== 'tag') data[k] = cached[k];

      at getWrapped (src/types/lazy.ts:14:22)
      at Object.get tag [as tag] (src/types/lazy.ts:9:15)
      at src/show.ts:6:16
      at src/show.ts:24:47
      at src/show.ts:31:63
          at Array.map (<anonymous>)
      at src/show.ts:31:14
      at src/show.ts:24:47
      at src/show.ts:31:63
          at Array.map (<anonymous>)
```

```
  ● undefined › ~: CustomGuardConstraint

    TypeError: Cannot read property '_someClassTag' of undefined

      57 |   constructor(public n: number) {}
      58 |   public _someClassTag = SOMECLASS_TAG;
    > 59 |   public static isSomeClass = (o: any): o is SomeClassV2 => o._someClassTag === SOMECLASS_TAG;
         |                                                               ^
      60 | }
      61 | 
      62 | const runtypes = {

      at Object.<anonymous>.SomeClassV2.isSomeClass (src/index.spec.ts:59:63)
      at Object.Constraint.runtype_1.create.tag [as validate] (src/types/constraint.ts:29:22)
      at assertRejects (src/index.spec.ts:748:26)
      at Object.<anonymous> (src/index.spec.ts:207:49)
```

```
  ● [null,null,null] › ~: 3

    TypeError: Cannot convert a Symbol value to a string

-- investigation of this one reveals that the problematic value is [ Symbol(0), Symbol(42), Symbol() ]
```

(note that line numbers and exact stack traces may be inaccurate due to the changes I have been making)

The tests previously got away with this because any exception was considered to be correct. This may also go some way to explaining why the library performs poorly speed-wise.

I suggest adding exception message checking to the automated tests and fixing these bugs (especially the call stack size exceeded bugs).

**Comment by pelotom** [comment]
This sounds not great. It's not clear to me how you're seeing these erroneous exceptions though. A PR which at least causes the testcases to fail when the wrong exceptions are thrown would be welcome.

**Comment by davidje13** [comment]
OK, I can put something basic together to flag them up. It might not be pretty though.

I observed them here because I swapped out all the exception logic for returns, which meant the only remaining exceptions are the unexpected ones (and without the try/catch logic, they get through now). Of course that means that some might actually have been caused by mistakes I made while doing that, but after investigation I'm fairly confident that's not the case, and these bugs have always been present.

**Comment by pelotom** [comment]
>I observed them here because I swapped out all the exception logic for returns

This is probably what we should do anyway, i.e. use `validate` instead of `check` in test cases.

**Comment by davidje13** [comment]
Even that on its own wouldn't reveal these, since `validate` has a `catch` which doesn't discriminate based on exception type, so all would get swallowed and returned as an object anyway. In the PR I made *all* `catch` blocks check exception type, both in the tests and the code itself.

But yes if the code can be updated to have `validate` as first-class and `check` as the wrapper, I fully agree that the tests would be better written using `validate` rather than `check`.

**Comment by pelotom** [comment]
> But yes if the code can be updated to have `validate` as first-class and `check` as the wrapper, I fully agree that the tests would be better written using `validate` rather than `check`.

That will hopefully be the outcome of https://github.com/pelotom/runtypes/pull/99.

**Comment by davidje13** [comment]
This seems to have been resolved now, so closing
