### ISSUE TITLE
Dictionary type and Cypress.io mismatch

### ISSUE THREAD

**Issue by mdenti** [pelotom/runtypes#104]
Hello,

I met this problem when mixing Cypress.io tests and runtypes:
while trying to verify the response of an API call, I passed the value returned by a [.should()](https://docs.cypress.io/api/commands/should.html) to a `Dictionary(...).check()` and was met with this rejection:
```
Expected { [_: string]: ... }, but was [object Object]
```
This wouldn't be a problem if it wasn't that the response was crafted on purpose for creating the test by using the same type.

I dug into the runtypes code and found that [this is the failing check](https://github.com/pelotom/runtypes/blob/a37f13548f3f9204415409e06fa97617b7b76159/src/types/dictionary.ts#L35).

Here's the type definition from Cypress.io of the object passed on by the `.should()`
```
interface ObjectLike {
  [key: string]: any
}
```

Is there any way to get this passing by using the Dictionary? I only know the shape, not the exact properties of the object, so this is troublesome..
Could it be enough for a Dictionary to be of the same shape as an object without it being *exactly* an Object?

Thanks!

**Comment by pelotom** [comment]
`Dictionary` is intended to match simple objects which map strings to values; this seems to be some sort of class instance. If you don't need to validate anything in particular about the cypress object, maybe `Unknown` would be a better choice?

**Comment by mdenti** [comment]
> `Dictionary` is intended to match simple objects which map strings to values; this seems to be some sort of class instance.

I don't know where the class comes from.. it seems to be a plain `Object`.. maybe cypress adds some extra functions to its object prototype? it does say that it's a `[object Object]`. 
It being a strict isObject check was also not what I expected of `Dictionary`, and the error message that it throws also does not say about it.

> If you don't need to validate anything in particular about the cypress object, maybe Unknown would be a better choice?

Unfortunately the values are some pretty complex structures that I would really like to validate.. my dictionary is essentially an ID-keyed map. It's also, at the same time, a property of a much bigger object.

The work-around I've used so far is that I don't use the `.guard()` or `.check()`, but instead make my own function where I loop over the properties of the dictionary with `for (let prop in dict)` and then check both the `prop` and the `dict[prop]` for correct types.. but it's not pretty (because of how big and complex the parent object is), and was what I wanted to avoid when using runtypes..

**Comment by pelotom** [comment]
You can always define your own custom runtype with

```ts
const MyDictionary = Unknown.withConstraint(x => /* ... your check here ... */);
```

**Comment by mdenti** [comment]
hmm I guess I could do that.. maybe define a separate `Dictionary`-like runtype using the [`create`](https://github.com/pelotom/runtypes/blob/a37f13548f3f9204415409e06fa97617b7b76159/src/runtype.ts#L71) function instead (if I'm able to) .. otherwise I'd probably need to wrap the `withConstraint` into a function that accepts the value runtype as parameter..

I'll try it out. thanks!

**Comment by pelotom** [comment]
> hmm I guess I could do that.. maybe define a separate `Dictionary`-like runtype using the [`create`](https://github.com/pelotom/runtypes/blob/a37f13548f3f9204415409e06fa97617b7b76159/src/runtype.ts#L71) function instead (if I'm able to) .. otherwise I'd probably need to wrap the `withConstraint` into a function that accepts the value runtype as parameter..
> 
> I'll try it out. thanks!

The `create` function is intended to be internal since the set of runtypes is closed. It's perfectly valid to make a parameterized runtype in the way you mentioned using a constraint:

```ts
function MyDict<V extends Runtype>(Value: V) {
  return Unknown.withConstraint(x => /* check values using Value */);
}
```

**Comment by mdenti** [comment]
> The create function is intended to be internal since the set of runtypes is closed.

alright, then the other option it is! :)

**Comment by mdenti** [comment]
I'm closing this since there's nothing to do about it on runtypes' side, thanks @pelotom for the help!

here's what I went with, in case anyone ever meets the same problem:
```
import { Runtype, Unknown, String } from 'runtypes';
import show from 'runtypes/lib/show';

/**
 * Validates that a value is a Number... -ish.
 */
export const NumberLike = String.withConstraint((x) => {
  return !isNaN(+x) || `Expected NumberLike, but was ${x}`;
});

/**
 * Validates that a value is a Dictionary object with keys of
 * type keyType and values of type valueType.
 */
export function Dictionary<K extends Runtype, V extends Runtype>(keyType: K, valueType: V) {
  return Unknown.withConstraint((x: unknown) => {
    if (x === null || x === undefined) {
      return `Expected Dictionary but was ${x}`;
    }

    if (typeof x !== 'object') {
      return `Expected 'object', but was '${typeof x}'`;
    }

    for (const k in x) {
      try {
        keyType.check(k);
      } catch (e) {
        return `Expected Dictionary key to be ${show(keyType.reflect)}, but was ${k}`;
      }

      try {
        valueType.check((x as any)[k]);
      } catch (e) {
        return `Expected Dictionary value to be ${show(valueType.reflect)}, but was ${(x as any)[k]}`;
      }
    }
    return true;
  });
}
```

to be used e.g. like `const CustomType = Dictionary(NumberLike, OtherCustomType)`.
