### ISSUE TITLE
Benchmark testing

### ISSUE THREAD

**Issue by moltar** [pelotom/runtypes#105]
Hi Tom,

I have been using `runtypes` and other similar runtime type checking libraries on various projects.

I decided to run some benchmarks on all of these libraries and do a write up about all of the options and pros and cons of each.

My preliminary results are [published in this repo](https://github.com/moltar/typescript-runtime-type-benchmarks).

I was wondering if you could take a look at that repo and see if the usage is fair and if I am not using the library in some disadvantaged way.

Here is `runtypes` specific test: https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/cases/runtypes.ts

The goal is to get the object validated and type guarded or returned type established.

Thanks!

**Comment by pelotom** [comment]
IIRC @gcanti did a similar benchmark and arrived at similar conclusions (just comparing `runtypes` and `io-ts` I believe), so this doesn't surprise me too much. If I had to guess using exceptions as the validation mechanism is probably contributing to the poor relative performance, so it may be interesting to re-run this test after #99 is merged.

**Comment by pelotom** [comment]
Update: #99 has been merged and released as `v4.0.2`.

**Comment by moltar** [comment]
@pelotom thanks for the update! I have posted the results in the PR comments.
