### ISSUE TITLE
JSDoc + Runtypes?

### ISSUE THREAD

**Issue by justingrant** [pelotom/runtypes#106]
Is there any way to put [JSDoc](https://jsdoc.app/) annotations on properties of a `Record` runtype so that documentation will show up when you hover (in VSCode) over a property after the runtype has been cast to `Static<>`?

I assume that the answer is "no" but in case there's some cool Jedi trick someone has figured out, I'd love to learn what it is.

**Comment by pelotom** [comment]
No... that would require comments to be incorporated into the type system somehow.

**Comment by justingrant** [comment]
Yep, that's what I assumed too. Bummer. Closing.

**Comment by patarapolw** [comment]
How about +Webpack +ts-loader; or some approaches that uses `require('typescript')` directly?
