### ISSUE TITLE
Contract for async function

### ISSUE THREAD

**Issue by artalar** [pelotom/runtypes#114]
How can I describe the result of an async function?

For example:

```ts
const fetchSignIn = t
  .Contract(
    Login,
    Password,
    // best place for type declaration
    // here we need possibility to describe runtype `SignInResponse`
    t.InstanceOf(Promise)
  )
  .enforce(async (login, password) => {
    const response = await request('/sign-in', {login, password})
    // inline `check` unreliably if we has a few result branches 
    return SignInResponse.check(response)
  });
```

**Comment by pelotom** [comment]
I'm not sure how this might work. Open to ideas...

**Comment by artalar** [comment]
May be

![example](https://user-images.githubusercontent.com/27290320/67399721-54acb080-f5b5-11e9-9b26-e91488f1e9d0.png)

**Comment by pelotom** [comment]
Hm, it's not a runtype though, it's a type of contract...

**Comment by artalar** [comment]
I mean when we call `check` with a promise - it adds `then(fulfilled.check)`.
With these solutions we may describe contract so:
```ts
const fetchSignIn = t
  .Contract(
    Login,
    Password,
    t.Async(SignInResponse)
  )

```

**Comment by zhaoyao91** [comment]
Oops, AsyncContract is great. I just about leaving when suddenly found this issue. Why not add it to the readme document?
