### ISSUE TITLE
Merge multiple Record types when combining with `And` ?

### ISSUE THREAD

**Issue by justingrant** [pelotom/runtypes#127]
One minor problem with runtypes is that static types sometimes look confusing in VS Code's intellisense (the type declaration shown in the editor when hovering over the static type).  I see this most when combining multiple `Record` and/or `Partial` runtypes together with `And` when trying to simulate `extends` of an interface, or to combine optional and required properties of the same interface. 

Ideally, `And`s of sibling `Record`s and `Partial`s would be merged into a more readable static type. Is this possible today?  If not, is the confusing display an inherent limitation of TypeScript's handling of intersection types, meaning that cleaner intellisense would require changes to TS not runtypes?

Repro:
```typescript
const RuntypeA = Record({ x: String }).And(Record({ y: Number }));
type StaticA = Static<typeof RuntypeA>;
```

Expected: when you hover over `StaticA` in the VS Code editor, you see this:

```typescript
type StaticA = {
    a: string;
    b: number;
}
```

Actual: when you hover over `StaticA` in the VS Code editor, you see this:

```typescript
type StaticA = {
    a: string;
} & {
    b: number;
}
```

**Comment by pelotom** [comment]
Yes, I think this is a limitation we have to accept for the time being. It would be nice if TypeScript could normalize a type like `{ x: X } & { y: Y }` to `{ x: X; y: Y }`; I made [a related issue](https://github.com/Microsoft/TypeScript/issues/20267) a while back which was resolved, but I think it's worth making a new one focused on this use case.

**Comment by KingDarBoja** [comment]
Was going to ask the same thing but seems that no new issue has been opened regarding this issue.

**Comment by benvan** [comment]
I had a similar issue - an approach i've found that works:

```
type StaticA = {
    a: string;
} & {
    b: number;
}

// Flatten an intersection type by merging keys:
type Flatten<T> = T extends Record<string,any> ? { [k in keyof T] : T[k] } : never

// use it:
type WhatYouWant = Flatten<StaticA>
```

When you hover over this (in my editor), it shows:
![image](https://user-images.githubusercontent.com/387597/107860019-19cb2d80-6e35-11eb-96b7-969775dba64a.png)

**Comment by yuhr** [comment]
Once #113 has been released, you can use `Record({ x: String, y: Optional(Number) })` which results in `{ x: string; y?: number | undefined; }`. Hence the static type of `Record({ x: String }).And(Record({ y: Number }))` shall be left as is.

**Comment by Masyaka** [comment]
> I had a similar issue - an approach i've found that works:
> 
> ```
> type StaticA = {
>     a: string;
> } & {
>     b: number;
> }
> 
> // Flatten an intersection type by merging keys:
> type Flatten<T> = T extends Record<string,any> ? { [k in keyof T] : T[k] } : never
> 
> // use it:
> type WhatYouWant = Flatten<StaticA>
> ```
> 
> When you hover over this (in my editor), it shows: ![image](https://user-images.githubusercontent.com/387597/107860019-19cb2d80-6e35-11eb-96b7-969775dba64a.png)

Thanks! Was looking for this solution quite long.

**Comment by yuhr** [comment]
Additional solution 1: recreating a `Record`

```typescript
const RuntypeA = Record({
  ...Record({ x: String }).fields,
  ...Record({ y: Number }).fields,
})
type StaticA = Static<typeof RuntypeA>
// type StaticA = {
//     x: string;
//     y: number;
// }
```

Additional solution 2: `extend` (<https://github.com/pelotom/runtypes/issues/238#issuecomment-827824249>)

```typescript
const RuntypeA = Record({ x: String }).extend({ y: Number });
type StaticA = Static<typeof RuntypeA>
// type StaticA = {
//     x: string;
//     y: number;
// }
```

To be clarify, what I meant [here](https://github.com/pelotom/runtypes/issues/127#issuecomment-805429786) is, TypeScript doesn't do this by default, so neither do we.
