### ISSUE TITLE
Expanding "withConstraint" with parent object

### ISSUE THREAD

**Issue by shane-lab** [pelotom/runtypes#130]
I'd like to post this here as a feature request that expands the static `withContraint` with "dynamic constraints".

I'd be nice if you could control the behaviour of a constraint based on an other value in the same object, e.g. a `Record`.

Here's an example:

```ts
import * as rt from 'runtypes';

const SomeRecord = rt.Record({
  x: rt.Boolean
  y: rt.Array(rt.Unknown).withConstraint((arr: any[], /* e.g. typeof this */ parent) => !parent.x : true ? arr.length);
});

const someObj = { x: true, y: [] };
SomeRecord.check(someObj); // validation error, someObj.y is empty
```
Based on the value of `someObj.x`, I can make an other value have a dynamic constraint.

**Comment by kim366** [comment]
What is the status on this? I found myself needing this in two places
