### ISSUE TITLE
How to create an optional any field ? Union(Unknown, Undefined) discards the Undefined

### ISSUE THREAD

**Issue by paduc** [pelotom/runtypes#136]
I'm trying to add a property to my schema which can either be anything or not defined at all (optional).
When using Unknown to allow the "anything" part, the "optional" aspect is discarded and Typescript requires that optionalField be included. 

```typescript
const mySchema = Record({
   id: String,
   optionalField: Union(Unknown, Undefined)
})

type MyType = Static<typeof mySchema>

// => 
MyType {
   id: string
   optionalField: unknown
}
```

What I would expect is :

```typescript
// => 
MyType {
   id: string
   optionalField: unknown | undefined
}

// or 
MyType {
   id: string
   optionalField ?: unknown
}
```

**Comment by paduc** [comment]
I succeeded with the following technique, though I still don't understand why Union(Unknown, Undefined) doesn't work. 

```typescript
const mySchema = Record({
   id: String
}).And(Partial({ optionalField: Unknown })

type MyType = Static<typeof mySchema>

// => 
MyType {
   id: string
} & { 
   optionalField ?: unknown
}

**Comment by yosbelms** [comment]
There is a PR for this https://github.com/pelotom/runtypes/pull/131,

**Comment by yuhr** [comment]
> though I still don't understand why Union(Unknown, Undefined) doesn't work.

Because that's how TypeScript works. See https://github.com/pelotom/runtypes/pull/113#issuecomment-544199694. The technique you described is the correct way to achieve what you want to do.

**Comment by yuhr** [comment]
FWIW #113 has been merged, so you will be able to use following syntax in the near future:

```ts
const mySchema = Record({
   id: String,
   optionalField: Optional(Unknown)
})

type MyType = Static<typeof mySchema>

// => 
MyType {
   id: string
   optionalField?: unknown
}
```
