### ISSUE TITLE
How to represent NonNullable<T>

### ISSUE THREAD

**Issue by jraoult** [pelotom/runtypes#139]
I'm probably over thinking this, but in spite of my experience with runtypes I can't think of a way to write a `RtNonNullable` that would match this:
```ts
type NonNullable<T> = T extends null | undefined ? never : T;
```

And then use it like:
```ts
// this works
const example: string = RtNonNullable.check("test");

// this throws at runtime
const example: string = RtNonNullable.check(null);
```

**Comment by petr-motejlek** [comment]
Hi, I have, like you, been trying to see where I can take `runtypes`, which I think is a really cool thing that I would like to use more and more. From the experience I've gather in the past couple days, I think I will have to write a couple helpers for myself, to make it even more useful. But as a base, it works good enough.

For the use case that you describe, I've created my own guard, and used that as a type. Now, this obviously overcomplicates it by preventing undefined and null and partial (and I am dealing with a object properties), but you can easily extract the part that only prevents null :)

Now, like you, I am still new to this, and actually to TypeScript and JavaScript in general, too. So, there is definitely a better way to do the same :) But writing custom guards seems to be the way. (BTW the generics I am using come from the cool `tsdef` library).

```typescript
export const $Config = $ConfigOptions.withGuard((cfg): cfg is RequiredProps<
  NonNilProps<NonUndefinedProps<ConfigOptions>>
> => {
  const optionMissing = Object.entries($ConfigOptions.fields).some(
    ([k]) => !(k in cfg)
  );

  return (
    !optionMissing &&
    !Object.entries(cfg)
      .filter(([key]) => key in $ConfigOptions.fields)
      .some((value) => value === undefined || value === null)
  );
});
```

**Comment by jraoult** [comment]
> Now, like you, I am still new to this

😀 @petr-motejlek , actually I'm not new with _runtypes_ at all and I think in this case it is what played against me. As a new user you get to read the doc way more than me these days and I missed the introduction of the `withGuard` method. Although I should have thought about the `withConstraints` one.

Many thanks for putting me in the right direction, here's the result where I emulate the core type `NonNullable`:
```ts
const isNotNull = <T>(obj: T): obj is NonNullable<T> => {
  return obj != null;
};

const RtNonNullable = <A>(rtype: rt.Runtype<A>) =>
  rtype.withGuard(isNotNull);
```

and the one with constraints for the record:
```ts
const RtNonNullable2 = <A>(rtype: rt.Runtype<A>) =>
  rtype.withConstraint<NonNullable<A>>(obj => obj != null);
```

**Comment by petr-motejlek** [comment]
Glad I could've helped.

**Comment by yuhr** [comment]
Seems already resolved, closing.
