### ISSUE TITLE
Typed keys for object

### ISSUE THREAD

**Issue by shikaan** [pelotom/runtypes#143]
Hello,

I am trying to mimic the following behaviour

```typescript
type Thing = 'thing1' | 'thing2'

type Lol = {
  [key in Thing]?: string
}
```

But `Record` has fixed keys and `Dictionary` only allows strings and numbers. 
Is there a way to achieve this?

**Comment by jraoult** [comment]
@shikaan you might be interested in: https://github.com/pelotom/runtypes/issues/79

**Comment by b-zurg** [comment]
What about just a string key like 

```ts
type Lol = {
  [key in string[: string;
}
```

I can't figure out how to do that.

**Comment by yuhr** [comment]
Once #193 get released, you can pass a `Union` as `Dictionary` key type:

```ts
const Thing = Union(Literal("thing1"), Literal("thing2"))
const Lol = Dictionary(String, Thing)
type Lol = Static<typeof Lol>
// type Lol = {
//     thing1: string;
//     thing2: string;
// }
```

But this way you can't "optionalize" them, so you still need some workarounds like the ones described here #160 (I don't know if it works for you, FWIW).
