### ISSUE TITLE
How to omit keys from a record?

### ISSUE THREAD

**Issue by papaia** [pelotom/runtypes#148]
Is there a way to omit keys from a Record type?
What I mean is something similar to [TypeScript's utility `Omit` type](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk), but for runtypes.

An example use could be:
```ts
import { Record, Static, String } from 'runtypes';

const Options = Record({
  url: String,
  token: String,
});

class Base {
  constructor(options: Static<typeof Options>) {}
}

const ExtendedOptions = Options.Omit('url');

class Extender extends Base {
  // here, url is default in the class
  constructor(options: Static<typeof ExtendedOptions>) {
    super({ url: 'https://example.com', ...options });
  }
}
```

**Comment by pelotom** [comment]
There isn't currently, but it seems like a reasonable idea, would you like to make a PR?

**Comment by Papaia** [comment]
I am still wrapping my head around the source code, but sure!

**Comment by Papaia** [comment]
Hey @pelotom, sorry but I can't really, could you implement it?

**Comment by ivawzh** [comment]
yo @pelotom, I spent an hour on `pick` and `omit`. 
Please have a look at the PR 👉 https://github.com/pelotom/runtypes/pull/161
