### ISSUE TITLE
Any reason for missing asReadonly on Partial?

### ISSUE THREAD

**Issue by kkelk** [pelotom/runtypes#152]
`asReadonly()` only seems to exist on `Array` and `Record` types. Would it be easy to extend this to support `Partial` as well? e.g. I'd like to be able to do:
```typescript
Record({
  required: Number
}).asReadonly().And(Partial({
  optional: Number
}).asReadonly());

// -> {readonly required: number;} & {readonly optional?: number | undefined;}
```

**Comment by pelotom** [comment]
That's reasonable, would you like to make a PR?
