### ISSUE TITLE
hasKey (via new Discriminated Union code) throws when value being validated is null

### ISSUE THREAD

**Issue by NMarrero** [pelotom/runtypes#154]
The new Discriminated Union code in 4.3.0 fails when value is null due to a bug in hasKey in https://github.com/pelotom/runtypes/blob/master/src/util.ts. 

Called from https://github.com/pelotom/runtypes/blob/master/src/types/union.ts#L996

If value is null, in ```hasKey``` ```typeof value === 'object'``` is true (thanks Javascript!) so it throws an exception when using the ```in``` operator.

Here's a small example: https://codesandbox.io/s/charming-dubinsky-x2mpy?file=/src/index.ts

**Comment by pelotom** [comment]
Hi NMarrero, thanks for the bug report. Would you be interested in making a PR to fix it?
