### ISSUE TITLE
Option for .guard() and .check() to detect abundant properties

### ISSUE THREAD

**Issue by Remirror-zz** [pelotom/runtypes#169]
Recently I came across a case similar to the following:
I had declared a runtype with an optional property
```
const Person = rt.Record({
  'name': rt.String,
}).And(rt.Partial({
  'birthyear': rt.Number,
}));
```
but then mistakenly created an object
````
const person = {
  'name': 'Patrick',
  'age': 31,
};
````
I long did not realize this because `Person.guard(person)` still returns `true`. This is understandable because `person` does in fact have all required properties (`name`), but I wished it would spot and criticize the abundant property (`age`).

TypeScript in fact always complains in such cases; e.g.
`const person: {'name': string, 'birthyear'?: number} = {'name': 'Patrick', 'age': 31};`
won't compile.

Maybe there should be an additional argument for `guard()` and `check()` for this purpose?

**Comment by stepchowfun** [comment]
This would also be great for security. I use runtypes on a server to validate input from untrusted clients. It would be nice if, after validating the untrusted input, I could pass it to library functions that e.g. accept an "options" object without worrying about the client setting extra options I didn't expect. Currently my approach is to just make a copy of the user input with only the fields that are declared in the type, but this is very manual and error-prone.

**Comment by yuhr** [comment]
Let's track this at #41.
