### ISSUE TITLE
exposing fields on a Runtype<R> or the Reflect object

### ISSUE THREAD

**Issue by djpeach** [pelotom/runtypes#173]
fields is a key on the Runtype<R> object, but is not publicly exposed. We have need to use it in order to build a specific type from a larger type with more properties than we need. For example, the object A comes into our server, and from that, we want to build object R and validate that as a Record<R>. If it is valid, that means all the properties existed on A that we needed and we can pass on the new object of type R to our next handler that needs it.

What we currently do is is run `.validate()` on an object we construct with lodash's `.pick()` function:
```js
function demo(schema?: Runtype<R>) { 
    const largeObj: A = { ... <many properties> ... };
    const input = schema?.validate(_.pick(largeObj, Object.keys(schema.fields)));
    if (input.success) {
        nextHandler(input.value);
    } else {
        throw new BadRequestError(`${input.key} - ${input.message}`);
    }
}
```

After some more digging, I found that you use reflect for this, but even then, the `fields` property is not exposed. We basically need the same thing you do here: https://github.com/pelotom/runtypes/blob/212f5e09dfe3461ab6abbe848567c006588e88d7/src/show.ts#L35. If there is a better way to do this whole process either, lmk. Thanks!

**Comment by djpeach** [comment]
Ok I finally ended up with 
```js
if (schema && schema.reflect.tag === "record") {
                const input = schema.validate(_.pick(req, Object.keys(schema.reflect.fields)))
                if (input.success) {
                    return input.value;
                }
                throw new BadRequestError(`${input.key} - ${input.message}`);
            }
```

but i feel there should be a better way to do this.

**Comment by yuhr** [comment]
You're doing right thing at this time. I believe what you want to do is essentially composed of two steps:

1. Pick specific field from a `Record`. This will be better handled by #161.
2. Strip off unwanted properties after validation. [Object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring) should fit your use case.

So maybe you want to track #161. `fields` is already an exposed API through `reflect`.

**Comment by yuhr** [comment]
Oh sorry I've been a bit misreading your code. Now I rethink the solutions are:

1. Validate relevant properties only. This is already done by just `Record({ ... }).validate(obj)`. You don't need to format the`obj` before validation.
2. Strip off unwanted properties. You may be interested in #132.
