### ISSUE TITLE
Exhaustive validate?

### ISSUE THREAD

**Issue by ctrlplusb** [pelotom/runtypes#174]
Thanks so much for this lib.

I am using it to enforce contracts at my client/server API boundary. 

One thing I was wondering about. Instead of bailing out early with the first mismatch whilst validating the types, is it possible to validate deeply and then produce an array of failed validations?

**Comment by supermacro** [comment]
See https://github.com/pelotom/runtypes/issues/8 and https://github.com/pelotom/runtypes/issues/39. Likely won't be implemented any time soon.

**Comment by yuhr** [comment]
Duplicate, closing.
