### ISSUE TITLE
Recommended way to model binary data in Runtypes?

### ISSUE THREAD

**Issue by justingrant** [pelotom/runtypes#178]
I'm adding a BLOB property to one of my Runtypes to store a profile picture image. Is there a recommended way to model binary data in Runtypes?  `InstanceOf(ArrayBuffer)`? Something else?

**Comment by yuhr** [comment]
Sorry for the late reply. The only option is to use `InstanceOf` for your use case.

If you want to look into the structure of binary data, you want to use some other packages like [`binary-parser`](https://www.npmjs.com/package/binary-parser). When we get #56 implemented we will be able to "embed" such parsers into runtypes.

**Comment by justingrant** [comment]
I finally got around to implementing this today, so your late reply was perfect! 🙏

What's funny is that I'd completely forgotten I'd posted this, so when I went Googling for answers I ended up at... my own 9-month-old question!  Adding a few keywords for future Google searchers: 
* Runtypes Buffer
* Runtypes Uint8Array
* Runtypes ArrayBuffer
* Runtypes binary
