### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by jeremyBanks** [pelotom/runtypes#179]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by OmgImAlexis** [comment]
Are there any work arounds for this until it's added to the package?

**Comment by jeremyBanks** [comment]
(Sorry if it's in poor taste to leave this comment here.) @OmgImAlexis This may not be useful to you, but for what it's worth: I switched from Runtypes to [Zod](https://github.com/colinhacks/zod) for bigint support, and have been satisfied with it. (At least after [this initial hiccup](https://github.com/colinhacks/zod/pull/237)).

**Comment by OmgImAlexis** [comment]
https://github.com/pelotom/runtypes/pull/185/files

**Comment by akutruff** [comment]
Hmmm.. last commit was from July of last year, and there's a small queue of pull requests.  This project still active?
