### ISSUE TITLE
importing `Record` destroys Record interface

### ISSUE THREAD

**Issue by patarapolw** [pelotom/runtypes#180]
![record-is-dead](https://user-images.githubusercontent.com/21255931/101213772-85fb1980-36ad-11eb-8792-8a42ea5f1a70.png)

Some of the solutions,

```ts
import { Dictionary, Record as Record_, Static, String, Unknown } from 'runtypes';
import * as t from 'runtypes';

type MyRecord<T> = {
  [k: string]: T
};
```

**Comment by yuhr** [comment]
Yes of course. Importing `Record` from `runtypes` shadows TypeScript's built-in `Record` type alias. I think it's not an issue as you have already found the solutions.
