### ISSUE TITLE
How to check for Any?

### ISSUE THREAD

**Issue by annmirosh** [pelotom/runtypes#181]
Hello!

How can I check that one of the properties is an object? Let's say I described the following type:

const Person = Record({
    name:String,
    age: Number,
    body: // what should I use here?
});

body is object - it can be filled with any values or empty ({}), but cannot be null or undefined

How I can describe it using runtypes?
Thanks!

**Comment by cldellow** [comment]
I also needed this, where I want to permit an opaque dictionary. eg `{}` or `{foo: 1, bar: "two", baz: { quux: [] }}` should both be accepted.

`Dictionary(Unknown, 'string')` is pretty close, although it permits `null` and `undefined` at compile-time [although not in the default validator -- perhaps this is a bug?]

```typescript
import { Dictionary, Record, Static, String, Unknown } from 'runtypes';

const X = Record({
  foo: Dictionary(Unknown, 'string')
});
type X = Static<typeof X>;

// Good: These fail to validate.
console.log(X.validate({}));
console.log(X.validate({foo: 1}));
console.log(X.validate({foo: null}));
console.log(X.validate({foo: undefined}));

// Good: These validate.
console.log(X.validate({foo: {}}));
console.log(X.validate({foo: {bar: 1}}));

// Good: These fail at compile time.
// const goodFooMustBePresent: X = {};
// const goodForbidsNonObject: X = { foo: 1 };

const goodPermitsEmptyObject: X = { foo: {} };
const goodPermitsArbitraryObject: X = { foo: {bar: 1, baz: { quux: false } } };

// Bad: These pass at compile time :(
//      They would fail the constraint check at runtime.
const badPermitsNull: X = { foo: null };
const badPermitsExplicitUndefined: X = { foo: undefined };
```

**Comment by yuhr** [comment]
@annmirosh I'm sure what you want is not `Any` but `NonNull`, `NonUndefined` or similar thing. Maybe we'd implement some ways to "negate" runtypes in the future (along with https://github.com/microsoft/TypeScript/pull/29317 ?), but at this time the only option is `Unknown.withConstraint(x => x !== undefined && x !== null)`.

@cldellow I can't confirm that your last two lines "pass at compile time", at least in `runtypes` 5.0.1 and TS 4.2.3. It expectedly emits static type-checking error. What versions of `runtype` and `typescript` are you using?

**Comment by yuhr** [comment]
Well, please file a new issue if you found a bug on it. I believe the OP's issue is resolved by my previous comment, so I'll close this.
