### ISSUE TITLE
Record Versioning / Changing properties

### ISSUE THREAD

**Issue by vgammieri** [pelotom/runtypes#186]
Hi,

I defined a complex type as a Record with many fields and now I need to change just a couple of fields type. The desiderata would be to generate a "version 2" of the original complex type and then merge it with the "version 1".

I started from here:

```
const MyTypeV1 = Record({
    version: Literal(1),
    .... 
    prop: SomeRuntype
})

const MyTypeV2 = Record({
    version: Literal(2),
    .... 
    prop: AnotherRuntype
})

const MyType = Union(MyTypeV1, MyTypeV2)

```

Then I could call MyType.check(x) and pass, as x, a record "version 1" or a record "version 2".

Now since the MyTypeV1 is very complex, and I want to avoid Copy&Paste the unmodified fields, there is a way to generate MyTypeV2 from MyTypeV1 ? 
```
const MyTypeV2 = MyTypeV1.Override({
    version: Literal(2),
    prop: AnotherRuntype
})
```

**Comment by yuhr** [comment]
I'd wrap it in a function in such case:

```ts
const MyType = (version: 1 | 2) => Record({
  version: Literal(version),
  prop: version === 1 ? String : Number
})
```

But that way you can't use `Static`:

```ts
const MyTypeV1 = MyType(1)
type MyTypeV1 = Static<typeof MyTypeV1>
// `MyTypeV1` above is invalid:
// type MyTypeV1 = {
//     version: 1 | 2;
//     prop: string | number;
// }
```

So if you miss it, you need an ugly hack like this:

```ts
const MyType = <V extends 1 | 2>(version: V) =>
  Record({
    version: Literal(version),
    prop: (version === 1 ? String : Number) as V extends 1
      ? typeof String
      : typeof Number
  })
const MyTypeV1 = MyType(1)
type MyTypeV1 = Static<typeof MyTypeV1>
// `MyTypeV1` above works expectedly:
// type MyTypeV1 = {
//     version: 1;
//     prop: string;
// }
```

Another option without wrapping in a function is:

```ts
const MyTypeCommon = Record({
  value: Literal("common")
})
const MyTypeV1 = MyTypeCommon.And(Record({
  version: Literal(1),
  prop: String
}))
const MyTypeV2 = MyTypeCommon.And(Record({
  version: Literal(2),
  prop: Number
}))
const MyType = Union(MyTypeV1, MyTypeV2)
```

I don't know how much your model is complicated, so please reopen and let me know if above options does not suit your case.
