### ISSUE TITLE
Continue maintainance?

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#189]
Hi @pelotom, is it still active? If you're tired of maintaining this repository, then I would love to become a collaborator and continue maintainance for you 😉

**Comment by pelotom** [comment]
Yes, life has become fairly hectic for me and I haven't had as much time as I'd like to maintain this. I'd be happy to add you as a collaborator!

**Comment by yuhr** [comment]
@pelotom Thanks! Actually this is very first time I become an outside collaborator of a major OSS project like this, so let me confirm:

- Release process is still left for you
- If so, I should ping you when a new release is needed, but which way do you prefer to be pinged?

**Comment by pelotom** [comment]
I invited you as a maintainer on NPM so you should be able to release as well.

**Comment by pelotom** [comment]
Thanks for taking up the torch, @yuhr!
