### ISSUE TITLE
Coerce isn't the right term

### ISSUE THREAD

**Issue by danielearwicker** [pelotom/runtypes#2]
Very minor nitpick, but coerce means forcing something to happen, or to change. Does runtime's `coerce` method do anything apart from checking that an object is already conforming to the type?

(Otherwise, very interesting library!)

**Comment by pelotom** [comment]
Fair enough, any suggestions? `validate` is probably the most correct term, but I already have that method as one that doesn't throw but returns a `Result` indicating success or failure. `validateOrThrow`? Kind of a mouthful.

**Comment by danielearwicker** [comment]
* `assertType`
* `checkType`
* `assert`
* `check`
* `requireType`
* `cast`

**Comment by pelotom** [comment]
I like `check`, short and sweet.
