### ISSUE TITLE
`Undefined` in `Record` breaking change in 5.2

### ISSUE THREAD

**Issue by tobyhei** [pelotom/runtypes#206]
Upgrading to 5.2 causes `Undefined` to fail for missing keys due to `Expected "$Field" property to be present, but was missing in $Record`

Reproduction:

```
/* eslint-disable new-cap */
import { Record, Undefined } from 'runtypes';

const Example = Record({
  test: Undefined,
});

describe('Example', () => {
  it('accepts empty object', () => {
    Example.check({});
  });
});
```

Passes in 5.1, and fails in 5.2 with  `ValidationError: Expected "test" property to be present, but was missing in test`

Broken in https://github.com/pelotom/runtypes/pull/113

**Comment by yuhr** [comment]
Oh... I assumed the old behaviour is a bug (see #182) compared to TS behaviour, but I understand this had to be marked as a breaking change as well. Please update your code using `Optional` or stick to 5.1, sorry 🙏🏻

**Comment by yuhr** [comment]
Added a [deprecation notice](https://www.npmjs.com/package/runtypes/v/5.2.0) for this version. Though I believe the new behavior is rather "correct" one and it wouldn't be any surprise to current users, as we had been providing a dedicated way to declare optional keys i.e. `.And(Partial(...))` until [5.1](https://github.com/pelotom/runtypes/tree/v5.1.0#optional-values).

**Comment by tobyhei** [comment]
Thanks 👍 

FWIW this was surprising to me as a current user. 
Most of the value of `runtypes` for us comes from validating types over the wire, since `undefined`s aren't always preserved in de/serialization this change does result in surprising behavior sometimes e.g default JavaScript stringify strips `undefined`s:

```
/* eslint-disable new-cap */
import { Record, Undefined } from 'runtypes';

const Example = Record({
  test: Undefined,
});

describe('Example', () => {
  it('accepts object with undefined', () => {
    const test = {
      test: undefined,
    };

    const roundTrip = JSON.parse(JSON.stringify(test));

    // works in both
    Example.check(test);
    
    // works in 5.1, fails in 5.2
    Example.check(roundTrip);
  });
});
```

**Comment by SimenB** [comment]
IMO `undefined` _should_ be treated differently from missing/optional (as you say to mirror TS), but it's still a breaking change 🙂 

Will you be publishing a v6 that includes that change? If not, will it be reverted so a new version with `.optional` can be released?

**Comment by yuhr** [comment]
I'm planning to publish v6 in a few days or a week, including the change. It will come with a bunch of new features and breaking changes (see [here](https://github.com/pelotom/runtypes/milestone/1?closed=1)), so I'm now testing it broadly.
