### ISSUE TITLE
runtypes returns integer out of range - for number size greater than int (2^32)

### ISSUE THREAD

**Issue by AmitFidler** [pelotom/runtypes#214]
I am getting this error: "integer out of range"
for validating a property as a number for this number for example:
6628412528.
it is bigger than 2^32 - 4 kb: 
2147483647
but way smaller than Number.MAX_SAFE_INTEGER:

9007199254740991

Please support the value of MAX_SAFE_INTEGER,
or for now please help me find a work around for processing those numbers
Thanks!

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by yuhr** [comment]
Hi, I can't reproduce the error. Could you elaborate on it as some example code or repo? I dare say our codebase have no chance to emit such error text, as there's no built-in runtype called `Integer` or some.

**Comment by AmitFidler** [comment]
correct, sorry my bad it returned from the db layer. 
closing, thanks!
