### ISSUE TITLE
Regression with optional properties in 5.2.0

### ISSUE THREAD

**Issue by skrud** [pelotom/runtypes#219]
Hey folks,

I've noticed a regression with regard to Optional properties as of runtypes `5.2.0`. Specifically, this issue: https://github.com/pelotom/runtypes/issues/60

Before `5.2.0`, we were able to specify a property with `.Or(Undefined)` and if the property was _missing_, it would still pass the type checks.
```
const myType = Record({
   foo: String,
   bar: String.Or(Undefined)
});

myType.check({ foo: 'abcd' }); // <-- This would pass.
```

However, after `5.2.0`, the above code would throw a validation error.

I'm aware of the workaround (using `.And(Partial({ bar: String }))`).

If this regression is _intentional_, then I think the documentation needs to be updated: https://github.com/pelotom/runtypes#optional-values

**Comment by yuhr** [comment]
This is intentional, see #206. We're sorry to surprise you with this breaking change. You're right, I'm going to append a caution about this to the readme.

Note that there exists one more handy workaround now: `Optional(String)`.

**Comment by skrud** [comment]
Ah, I only looked at "open" issues so I missed that one. Thanks for the
quick answer!

**Comment by yuhr** [comment]
Description added in the section. Thanks!
