### ISSUE TITLE
[Feature request] new shortcut `.nullable()` for `.Or(Null)`

### ISSUE THREAD

**Issue by ybiquitous** [pelotom/runtypes#222]
Hello, thank you a lot for this nice package! 🥰 

I have a suggestion to add a new shortcut `.nullable()` for `.Or(Null)`.
This is a simple shortcut function, which can reduce importing `Null`.

For example:

```diff
-import { String, Null } from "runtypes"
+import { String } from "runtypes"

-const Foo = String.Or(Null)
+const Foo = String.nullable()
```

What do you think about this?

If you consider it needless, feel free to close this issue.
Thank you.

**Comment by yuhr** [comment]
Thanks for the proposal, sounds reasonable. This should be available in the next minor version.

**Comment by ybiquitous** [comment]
Good news! I’m looking forward to the next version! 🙌

**Comment by ybiquitous** [comment]
@yuhr Thank you for implementing this feature! 😊
