### ISSUE TITLE
Support for custom classes?

### ISSUE THREAD

**Issue by SIGUSR97** [pelotom/runtypes#235]
Thats say I have defined a class `Foo` follows:
```ts
declare class Foo {
    public bar: number;
    public baz: string;
} 
```
Right now if I want to declare an Array of Foo's typescript would yell at me for doing that.
![image](https://user-images.githubusercontent.com/52692296/115642488-a3bfd700-a34d-11eb-91c5-fe0116cc2d0b.png)
Is It possible to have something like:
![image](https://user-images.githubusercontent.com/52692296/115642748-1c269800-a34e-11eb-85b9-36ed331205f9.png)
That way I can use my predefined classes instead of having to rewrite them with a `Record`, and internally it can be checked with the `instanceof` operator.

**Comment by yuhr** [comment]
Use `InstanceOf` runtype.

```ts
class Foo {
    public bar: number;
    public baz: string;
}

Array(InstanceOf(Foo))
```

Note that `instanceof` operator requires actual (JS level) class constructor, so it cannot be used with TS level `declare class`.
