### ISSUE TITLE
Add documentation for `InstanceOf`

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#237]
With #235 I've noticed that `InstanceOf` is undocumented in the readme.

**Comment by KingDarBoja** [comment]
Is this similar to what is described at [Zod InstanceOf](https://github.com/colinhacks/zod#instanceof) method?

Been looking for a way to declare a class and use it for creating base schemas to add some validations as DTOs for the server-side stuff and keep both client and server apps synced.

Like: 

```ts
export class AddressSchema {
  country: string;
  state: string;
  district: string; // Optional
  city: string;
  zip: string;
}
export class CompanySchema {
  id: string; // Primary ID
  name: string;
  address: AddressEntity[];
}

const CompanyRuntype = rt.InstanceOf(CompanySchema); // use as runtype!
```

If that's not the case, then my question could be related to #128 but for class definitions? __(although classes also generates interfaces)__

**Comment by yuhr** [comment]
> Is this similar to what is described at [Zod InstanceOf](https://github.com/colinhacks/zod#instanceof) method?

Yes, why not try it on [RunKit](https://npm.runkit.com/runtypes)? 😉 You can copy and paste this:

```ts
const rt = require("runtypes")

class AddressSchema {}
class CompanySchema {}

const AddressRuntype = rt.InstanceOf(AddressSchema); 
const CompanyRuntype = rt.InstanceOf(CompanySchema);

const address = new AddressSchema()
const company = new CompanySchema()

console.log(
    AddressRuntype.guard(address),
    AddressRuntype.guard(company),
    CompanyRuntype.guard(address),
    CompanyRuntype.guard(company),
)
```

> Been looking for a way to declare a class and use it for creating base schemas to add some validations as DTOs for the server-side stuff and keep both client and server apps synced.

I don't understand what you want to do exactly, but AFAICT `InstanceOf` just tries to validate the input using `instanceof` operator, and does not look it's content.
