### ISSUE TITLE
Record.extends?

### ISSUE THREAD

**Issue by SIGUSR97** [pelotom/runtypes#238]
I am trying to use runtypes to validate the inputs to when drawing a bunch of shapes, their parameters are designed as follows:

```ts
const BaseShapeParams = Record({
    x: Number,
    y: Number,
    width: Number,
    height: Number,
    rotation: Number,
});

const RectParams = BaseShapeParams;
const EllipseParams = BaseShapeParams;
```
However, for a polygon type and a star type I would need two additional fields, sides and ratio. Right now I see no way of extending to an existing `Record` directly. And I would have to do this:
```ts
const PolygonParams = Record({
    x: Number,
    y: Number,
    width: Number,
    height: Number,
    rotation: Number,
    sides: Number,
});

const StarParams = Record({
    x: Number,
    y: Number,
    width: Number,
    height: Number,
    rotation: Number,
    sides: Number,
    ratio: Number,
});
```

Which produces a lot of redundant code. I understand that you could do something like this:

```ts
const baseShapeParams = {
    x: Number,
    y: Number,
    width: Number,
    height: Number,
    rotation: Number,
} as const;

const PolygonParams = Record({
    ...baseShapeParams,
    sides: Number,
});
```

But it would still be helpful to be able to extend on an existing `Record` type. What I imagine could've been done is something like:

```ts
// typescript's static analysis recognizes this successfully
interface InternalRecord<
  O extends { [_: string]: RuntypeBase },
  Part extends boolean,
  RO extends boolean
> extends Runtype<RecordStaticType<O, Part, RO>> {
      extends<T extends { [_: string]: RuntypeBase }>(fields: T): InternalRecord<O & T, Part, RO>;
}

const PolygonParams = BaseShapeParams.extends({
    sides: Number,
});
/**
 * InternalRecord<{
 *     x: Number;
 *     y: Number;
 *     width: Number;
 *     height: Number;
 *     rotation: Number;
 * } & {
 *     sides: Number;
 * }, false, false>
 */
```

**Comment by yuhr** [comment]
Now available in v6.3.0 :wink:

**Comment by KingDarBoja** [comment]
What is the difference with the existing `.And()` method?

**Comment by yuhr** [comment]
@KingDarBoja

1. `.And()` returns an `Intersect`, while `.extend()` returns a `Record`. This difference is also reflected in their `Static` types, i.e. the former is inferred like `{ ... } & { ... }` and the latter is just `{ ... }`.
2. `.And()` can return an invalid runtype such as `Intersect(Record({ foo: Number }), Record({ foo: String }))`  if fields are incompatible, while `Record({ foo: Number }).extend({ foo: String })` detects it and notifies us as a compile-time error for each incompatible field, like `Type 'string' is not assignable to type 'number'.`.
3. If the above error was `@ts-ignore`d, it will result in a runtype which is just incompatible to the base runtype, not invalid, i.e. `Record({ foo: String })`.

**Comment by KingDarBoja** [comment]
Based on that explanation, seems like changing every `.And()` to `.extend()` provides more safety and better static types, which is something I have been looking for (never liked the inferred intersect when the type has several fields). Also enables better code organization if someone is looking to share runtypes between the server and the app using monorepo tools and such.

Outstanding job 🚀
