### ISSUE TITLE
Better info to explain where object doesn't match the RunType

### ISSUE THREAD

**Issue by NickR49** [pelotom/runtypes#260]
I have quite detailed RunType records for api responses. Unfortunately when something fails `record.check(values)` the exception message doesn't point out where the mismatch has occurred as follows -

```ValidationError: Expected { id: number; accessProfiles: { id: number; title: string; }[]; canEdit: boolean; clauseDetails: { id: number; documentId: number; documentTitle: string; documentType: string; documentStatus: string; documentLapseDate: string | null; documentExpiryDate: string | null; isCompliant: boolean; isRelevant?: boolean; isBreached: boolean; }[]; clauses: number[]; collections?: unknown[]; compliancePercentage: number; description: string | null; documentDetails: { id: number; type: string; title: string; status: string; lapseDate: string | null; expiryDate: string | null; clauseDetails: { id: number; isCompliant: boolean; isRelevant: boolean; isBreached: boolean; }[] | undefined; }[]; documents: number[]; filters?: { clause_ids: number[] | null; document_ids: number[] | null; document_statuses_f: string | null; document_types_f: string | null; due_from: null; due_relative_direction: ("+" | "-") | null; due_relative_duration: number | null; due_relative_start: number | null; due_to: null; expire_from: null; expire_to: null; favourited: boolean | null; ids: null; is_active: boolean | null; is_breached: boolean | null; is_completed: boolean | null; is_noncompliant: boolean | null; is_resolved: boolean | null; lapse_from: null; lapse_to: null; no_filter: boolean | null; owner_ids: number[] | null; watched: boolean | null; }; incidents: { id: number; documentId: number; documentTitle: string; documentType: string; documentStatus: string; documentLapseDate: string | null; documentExpiryDate: string | null; clauseId: number; }[]; isFavourited: boolean; isWatched: boolean; nbActiveDocuments: number; nbAllClauses: number; nbClausesWithIncidents: number; nbNonCompliantClauses: number; nbNonResolvedIncidents: number; owner: number; pins: { latitude: number; longitude: number; }[]; search?: null; tags: number[]; tasks: { id: number; documentId: number; documentTitle: string; documentType: string; documentStatus: string; documentLapseDate: string | null; documentExpiryDate: string | null; clauseId: number | null; incidentId: number | null; }[]; title: string; }, but was incompatible```

Nothing in the exception message narrows down the location of the mismatch - it just says `but was incompatible`.
Going through by hand trying to identify where a 65k JSON response doesn't match the record is painful.
It would be handy if it could say something simple like `but was incompatible because 'clauseDetails[52].id' was the wrong type` - even if it simply mentions the very first incompatibility it comes across and ignores the rest.

**Comment by okomarov** [comment]
@yuhr Can you provide a pointer on:
1. wether some level of the enhancement is achievable with minor changes?
2. the parts of the code to modify?

Or if the above requires major changes? 

I for instance would be happy to just report the leaf field only, i.e. instead of `clauseDetails[52].id was the wrong type` just `id was the wrong type` as that would already help narrow down the search immensely but would simplify the problem as you don't need the whole path of the object.

**Comment by yuhr** [comment]
We can implement this by changing here. I'd say it will be small thing.

https://github.com/pelotom/runtypes/blob/a3747472461dfc9db91e76724d92394b81ec5daf/src/util.ts#L61

But I wonder if you noticed `details` property of the error object. It contains an object that indicates where the validation failed exhaustively. For example:

```ts
const R = Record({ a: Literal('a'), b: Literal('b'), c: Literal('c') });
R.check({ a: 'b', c: 'c' });
```

Then you'll get this error output:

```
ValidationError: Expected { a: "a"; b: "b"; c: "c"; }, but was incompatible
    at ...
    <stack traces>
    at ... {
  code: 'CONTENT_INCORRECT',
  details: {
    a: 'Expected literal `a`, but was `b`',
    b: 'Expected "b", but was missing'
  }
}
```

**Comment by okomarov** [comment]
Oh that is great. I confirm that `yarn node build/test.js` produces the expected output. However, there seem to be **two related issues** here.

### First
The `ts-node-dev` truncates away the details and:
```
yarn ts-node-dev test.ts
```
produces only the main message:
```
ValidationError: Expected { a: "a"; b: "b"; c: "c"; }, but was incompatible
    at new ValidationError (/Users/okomarov/Documents/repos/myrepo/api/node_modules/runtypes/lib/errors.js:22:28)
    ...
```
where 
```
yarn run v1.22.10
ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
```

### Second
Even the transpiled `.js` called with `node` prints ONLY the main message. This is probably because we use some CLI shim to import CSV data and the `code` and `details` are lost for some reason.

**Comment by okomarov** [comment]
> We can implement this by changing here. I'd say it will be small thing.
> 
> https://github.com/pelotom/runtypes/blob/a3747472461dfc9db91e76724d92394b81ec5daf/src/util.ts#L61

While the workaround is to `console.log(err)` and make sure that if you chain errors, to use the `ValidationError`, I still think it makes sense to include the details into the main error message which is thrown. I would also add the details before the full shape of the type as that can be very very long (see OP's example). Happy to issue a PR is you agree @yuhr.

**Comment by yuhr** [comment]
Thanks, I agree and appreciate a PR. The message should be well-formatted and more informative than current implementation, for example, each detail should be printed line-by-line, then "For more info, see \`details\` property of the error object", and then the shape of the runtype at last (I don't require you to make the shape formatted as it must be quite a hard work).

**Comment by HzrdIRL** [comment]
@yuhr I've created a PR against this issue - let me know if I can clarify/improve it somehow.

**Comment by guyellis** [comment]
Thank you for doing this @HzrdIRL

**Comment by HzrdIRL** [comment]
Happy to pitch in and help out @guyellis 🙇

**Comment by andyfurniss4** [comment]
Any progress with this? Is the PR going to be merged?

**Comment by yuhr** [comment]
Sorry I'm quite busy now, there might be some progress around the next weekend though.

**Comment by MattiasMartens** [comment]
what i see is that `runtypes` does produce a detailed validation failure report under the hood, but it makes it a little hard for the consumer to access it. my code looks something like this:

```ts
const validationResult = MyRuntype.validate(asYaml)

if (!validationResult.success) {
  throw new Error(
    JSON.stringify((validationResult as Failure).details)
  )
}
```

it feels like the cast shouldn't be necessary there.
