### ISSUE TITLE
Dictionary with optional keys

### ISSUE THREAD

**Issue by tvald** [pelotom/runtypes#264]
I believe there is currently no way to create a dictionary with optional keys, since `Partial` can't be applied to a `Dictionary`. All keys are required for a runtype `Dictionary`.

Is this a bug or known gap, or am I missing how to achieve this?

```
// this works
type PartialDict = { ["bar"]?: string } // or Partial<Record<"bar", string>>
const dict: PartialDict = {}  // ok

// Dictionary is equivalent to { ["bar"]: string | undefined }
const RuntypePartialDict = Dictionary(Optional(String), Literal("bar"))
type RuntypePartialDict = Static<typeof RuntypePartialDict>

const rdict: RuntypePartialDict = {}
// Error: Property 'bar' is missing in type '{}' but required in type '{ bar: string | undefined; }'.ts(2741)
```

For comparison, a `Record` with an `Optional` value allows the omission of the corresponding key. However, in a real world scenario, `"bar"` would be a set of keys which makes it difficult to just define the type as a `Record`.
```
const T = Record({ bar: Optional(String) })
type T = Static<typeof T>

const foo: T = {}  // ok
```

**Comment by yuhr** [comment]
Hm, this should be a bug. Originally I just didn't intended `Optional` to be used within a dictionary, but it's a shame this doesn't work. We must support this.
