### ISSUE TITLE
Is there support for template literal types?

### ISSUE THREAD

**Issue by SlateDave** [pelotom/runtypes#268]
In Typescript there is a thing called [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). So I've made this example type:

```
type Owner = 'Bob' | 'Jeff';
type Dog = `${Owner}'s dog`;
```

The resulting union type of `Dog` now is `"Bob's dog" | "Jeff's dog"`.

Is there a way to create a corresponding runtype for this?

**Comment by yuhr** [comment]
Not an intuitive one, but you can achieve it by using `Constraint` runtype.

```ts

const Owner = Union(Literal('Bob'), Literal('Jeff'))
const Dog = String.withConstraint(
  s =>
    Owner.guard(s.match(/^(?<owner>.+)'s dog$/)?.groups?.owner) ||
    'invalid owner',
)

Dog.check("Bob's dog")
// OK

Dog.check("Alice's dog")
// ValidationError: Failed constraint check for string: invalid owner
```

I think it's better to add this as a separate runtype if possible (especially for the sake of correspondence to TS's type system), but I'm not sure how we should implement. Maybe we could use [tagged template](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates)?

**Comment by yuhr** [comment]
Hm, I thought it's concise to be able to write it like this:

```ts
const Owner = Record(Literal('Bob'), Literal('Jeff'))
const Dog = Template`${Owner}'s dog`
```

But then `Static<typeof Dog>` is not possible currently as TS doesn't populate `TemplateStringsArray` (the type of first parameter of the [tagged template function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates)) as a tuple of string literal types. My ideal behavior is suggested [here](https://github.com/microsoft/TypeScript/issues/33304#issuecomment-697977783), but it's not likely to be available at least in the near future.

That said, I confirmed runtime type checking is possible in the above syntax. I'm going to file a PR.
