### ISSUE TITLE
[Feature Suggestion]: `JSONRuntype`

### ISSUE THREAD

**Issue by AZMCode** [pelotom/runtypes#269]
I am currently building a library that often serializes and deserializes from JSON, with a user-given Runtype as a runtime check.
As it stands, it would be useful to have a (Compile-Time) runtype that can only be assigned JSON-serializable types, such that a runtype given by the user is constrained to only JSON-serializable runtypes.

A possible use case might be declaring a function like this:
```
import * as t from "runtypes";
export MyLibraryFunction(userRuntype:t.JSONRuntype):void{
    <some code here that uses the user-provided JSONRuntype>
}
```
And, in usage, the following would fail with a compile-time error:
```
import * as t from "runtypes";
import { MyLibraryFunction } from "myLibrary";
MyLibraryFunction(t.Undefined);
// Argument of type 'Literal<undefined>' is not assignable to parameter of type 'JSONRuntype'.
```
While the following would work fine:
```
import * as t from "runtypes";
import { MyLibraryFunction } from "myLibrary";
MyLibraryFunction(t.Null);
```
Since JSON cannot serialize `undefined` but it can serialize `null`

As it stands, it would only be a utility type, as it can be built by the user, but it would be really useful otherwise.
Perhaps, in future, other types representing other serialization  schemes could be added, like `YAMLRuntype` or `JOSSRuntype`.

**Comment by yuhr** [comment]
If I understand correctly, you just want a predefined static type for JSON. I'd suggest using a dedicated package for that, for example [`types-json`](https://www.npmjs.com/package/types-json), along with the exported interface `Runtype`.

```ts
import { JSONValue } from 'types-json'
import { Runtype, Undefined, Null } from 'runtypes'

const MyLibraryFunction = (userRuntype: Runtype<JSONValue>): void => {}
MyLibraryFunction(Null)
MyLibraryFunction(Undefined) // Type 'undefined' is not assignable to type 'JSONValue'.ts(2345)

```

**Comment by AZMCode** [comment]
Yes, that would be exactly what I want. Should've done a bit more research. Thanks for the pointer!
Closing

**Comment by AZMCode** [comment]
While the original idea and answer is still valid, it would be useful to have a runtime runtype that could check whether a given value is JSON-compatible
