### ISSUE TITLE
Dictionary(Number, Number) won't accept {1: 99, 2: 100}

### ISSUE THREAD

**Issue by NickR49** [pelotom/runtypes#272]
I'm having trouble with specifying the runtype for this shape - `clauseOrder: {1: 4065, 2: 4066, 3: 4067, 4: 4068}`

The TypeScript type is simply `clauseOrder: { [index: number]: number }`.

And using Runtypes I implemented it as - 
```
import { Number as RTNumber } from 'runtypes';
const ClauseOrderRT = Dictionary(RTNumber, RTNumber)
```
However, when I run `record.check(values)` I get `TypeError: global.Number is not a function`.

Any ideas?

**Comment by yuhr** [comment]
This error seemed like simply our mistake that we use `global` (must be fixed soon), which doesn't available in browsers, but in that case I guess it should be a `ReferenceError`, not a `TypeError`. What environment are you running the code in? Maybe `global.Number` is mocked or swapped elsewhere erratically.

And what is `record` you're saying? I can infer `record` is the `ClauseOrderRT`, but it's not assured. It would be even more helpful to address the issue, if you provide the ”underwater“ code.

BTW at least in the current versions of `runtypes`, strictly speaking, `Record` is a different kind of runtype than `Dictionary`.

**Comment by NickR49** [comment]
This code is being used in a React app (using Vite instead of CRA).
Actually now that you mention it I did have some temporary code after switching to Vite to get references to `global` in libraries working -
```
    <script>
      window.global = {};
      window.require = () => {}; // Temp fix for getting Recharts to work with Vite https://github.com/vitejs/vite/issues/3477
    </script>
```
I've changed this and the record check is now working -
```
    <script>
      let global = globalThis;
      window.require = () => {}; // Temp fix for getting Recharts to work with Vite https://github.com/vitejs/vite/issues/3477
    </script>
```

Thank you very much!

Just for completeness of information here's how I'm using the record check -

```
export const BackendDocumentRT = Record({
  id: RTNumber,
  clauseOrder: ClauseOrderRT.Or(Null),
}

export function loadDocument() {
        // Axios request here
        const document = checkTypes(
          BackendDocumentRT,
          response.data
        );
}

export function checkTypes<T>(
  record: Runtype<T>,
  values: unknown,
): T {
  try {
    return record.check(values);
  } catch (exception) {
    const message = `Runtypes exception: ${exception}`;
    if (import.meta.env.DEV) {
      console.log(message);
    }
    // Logs to Sentry here
    return values as T;
  }
}
```

**Comment by yuhr** [comment]
Closing as resolved. Thanks~
