### ISSUE TITLE
Forbid additional properties in Record?

### ISSUE THREAD

**Issue by liuxh0** [pelotom/runtypes#274]
It seems objects with additional properties are still conform to the type. For example:
```
const ExampleRunType = rt.Record({ x: rt.String});
const obj = ExampleRunType.check({x: "abc", y: "def"})
```
Is there a way to forbid additional properties, which achieves `"additionalProperties": false` in JSON Schema (https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties)?

**Comment by yuhr** [comment]
This is a long-stanting issue and tracked in #41, please subscribe to the thread.
