### ISSUE TITLE
How does this compare to io-ts ?

### ISSUE THREAD

**Issue by skyjur** [pelotom/runtypes#28]
Hi! Kudos for sharing this library. I'm doing some validation on incoming data from http API, and this made it so much easier, compared to implementing types, and then also validators.

I also found that another project [io-ts](https://github.com/gcanti/io-ts) seem to do very similar thing. I wonder if there are any fundamental difference to the taken approach?

**Comment by pelotom** [comment]
The goals are definitely similar... I created Runtypes as a library solution to the problem posed by https://github.com/Microsoft/TypeScript/issues/1573. After I posted about it there @gcanti let me know about `io-ts` which he had created around the same time. I’m not sure how much difference there is fundamentally; I’d say try them both and use whichever works best for you!

**Comment by ecamellini** [comment]
Also, I think `runtypes` does not allow custom decoding/encoding but just validation.

With `io-ts` you can for example validate that a certain value is a `string` and at the same time encode it into a `Date`, using https://gcanti.github.io/io-ts-types/modules/DateFromISOString.ts.html.

In https://gcanti.github.io/io-ts-types you find many custom codecs and you can also define your own.
