### ISSUE TITLE
Serialization/Deserialization of Runtypes

### ISSUE THREAD

**Issue by bradenhs** [pelotom/runtypes#30]
Love this library. We're thinking about using it to type and validate our api responses. One problem we've encountered though is that for very large response objects validation isn't fast enough (can take up to a few seconds in some cases). A possible solution we've come up with is using web workers to perform this validation since it isn't essential we know right away if the response json is invalid. Problem is getting the runtype into the web worker. If we could serialize/deserialize the runtype we'd be able to pass it to the worker. It seems like it'd be pretty trivial to serialize/deserialize a runtype provided it's representing json. Thoughts on this? Would serialization of runtypes be a feature you'd be willing to include in this library?

**Comment by pelotom** [comment]
I must admit I don't fully understand the use case. The whole idea with runtypes is that they are constructed at the beginning of your app and have known types (thus they can be used to extract static types). So I don't understand why you'd want to serialize them. Can't your web worker code just construct runtypes itself, without the need to have them serialized? I guess I would need to see an example to understand better what you're trying to do.

**Comment by bradenhs** [comment]
That's actually what we're doing now. Both the non-worker and worker code import the same runtypes individually. It's definitely a feasible solution. The only drawback is that it takes a little more explicit wiring of things together to make it work this way. It makes the code a little more tightly coupled and a bit less DRY. Having the ability to pass arbitrary serialized runtypes to a worker would simplify things.... so it's not a deal breaker but would be nice. I totally get it if you don't feel that's a compelling enough use case to include serialization within the library.

**Comment by pelotom** [comment]
I would say it probably doesn't rise to the level of compelling to me, but I will say that this sort of thing should be quite straightforward to do externally without changing the core library; that's what the [`Reflect`](https://github.com/pelotom/runtypes/blob/master/src/reflect.ts) type enables. See the [`show`](https://github.com/pelotom/runtypes/blob/master/src/show.ts) function for an example of writing a function against the runtime `Reflect` information of a `Runtype`. Basically you could write a recursive serializer / deserializer against `Reflect`. The only caveat is that some runtypes, e.g. `Constraint`, are inherently unserializable because their `Reflect` information contains executable code in a closure.

**Comment by bradenhs** [comment]
Thanks for the info! Depending on how things play out I may end up writing a serialize/deserialize function. If I do end up doing that would you consider a PR or would you prefer to keep serialization outside of the library?

**Comment by pelotom** [comment]
I think I would prefer to keep it external to the core library.

**Comment by cdaringe** [comment]
Just came here for this! I think it could be very useful. Consider the case where schema is built up by composing schemas from multiple sources, programatically. Studying code is not a great mechanism then to get a "feel" for what the schema is. `mySchema.toJSON()` to allow for printing a nice representation could lend itself for sharing full schemas in a flat, easy to grok format.

**Comment by cdaringe** [comment]
ah, I see `.show` on the RT prototype is now a thing. will experiment with that
