### ISSUE TITLE
Is there a way to omit everything that's not defined by the Record instance?

### ISSUE THREAD

**Issue by isaac-weisberg** [pelotom/runtypes#305]
For instance, if I have some rogue fields arriving from my client, and I would like to forward the object right into my MariaDB driver (which is of course a horrible idea), can I ask the Record to return a copy that has omitted everything it didn't know of?

**Comment by yuhr** [comment]
This will be covered by #191; related issues are #24 and #132. I'm working hard redesigning the `Transform` API now.

Closing as duplicate. Thanks!
