### ISSUE TITLE
Printable form of type from runtype?

### ISSUE THREAD

**Issue by koljagralla** [pelotom/runtypes#307]
I'm building a small framework for web applications and I use Runtypes for built in request validation. I'm a big fan of verbose error messages (at least on dev, prod is another thing).

I'd like to not just return the exception contents but also the whole structure of the Runtype when a validation error occurs. Maybe event with some sort of prose.  

In combination with #41 this would empower Runtypes be the complete solution to build stable, comprehensible APIs.

Is there already a way to do this that I did not see? If not, anybody else interested? I could work on a PR.

**Comment by yuhr** [comment]
Sorry for being late, let's track this at #236!
