### ISSUE TITLE
Fails to build with declaration `true`

### ISSUE THREAD

**Issue by timm-gs** [pelotom/runtypes#31]
The following simple example fails to build for me when setting `declaration` to `true` in TypeScript's `compilerOptions`.

Code:
```ts
import * as rt from 'runtypes';

export const Test = rt.Record({ });
```

`tsconfig.json`:

```json
{
  "include": [
    "src/conversion/test.ts"
  ],
  "compilerOptions": {
    "noEmit": false,
    "noUnusedLocals": true,
    "strict": true,
    "rootDir": ".",
    "outDir": "./lib",
    "declaration": true
  }
}
```

Error:
```
src/conversion/test.ts(3,14): error TS4023: Exported variable 'Test' has or is using name 'Record' from external module ".../node_modules/runtypes/lib/types/record" but cannot be named.
```

Any idea why that is?

**Comment by timm-gs** [comment]
But it works when I change the code to

```ts
import { Record } from 'runtypes';

export const Test = Record({ });
```

Might this be a TypeScript bug?

**Comment by pelotom** [comment]
This is a TypeScript gotcha:

https://github.com/Microsoft/TypeScript/issues/9944

Basically you always need to import any type which will end up appearing in your declaration file, whether you use it explicitly in your code or not.
