### ISSUE TITLE
`omit` properties of a `Constraint` or `Intersect`?

### ISSUE THREAD

**Issue by woifes** [pelotom/runtypes#317]
I often use `Interesect` or `Constraint` Records, which I want to modify on a different Place:

```
const myRuntype = Record({
    A: Number,
    B: Number,
}).withConstraint((r) => {
    return r.A > r.B || `A has to be bigger than B`;
});

const myOtherRuntype = myRuntype.omit("A");
```

I totally understand, that the constraint check will be unclear, if I remove a property involved in the check (I guess that is why the two types lose the `omit` or `pick`. Nevertheless I want "myOtherRuntype" to have a structure based on "myRuntype" so that typescript will not complain when I extend it afterwards. Is there a way of doing this? 
I mostly want to set optional properties to required (For this I atm interesct with a record which has the corresponding property as required):
```
const myRuntype = Record({
    A: Number.optional(),
    B: Number,
}).withConstraint((r) => {
    return r.A > r.B || `A has to be bigger than B`;
});

const myOtherRuntype = myRuntype.And(Record({ A: Number }));
```
But for the opposite case, so either removing or setting a property optional I am a bit lost.

I tried to find this question in the issues but it is difficult to formulate. I am sure there was an issue before.

**Comment by yuhr** [comment]
There's no straightforward way to do it like that. `Constraint` (and also `Intersect`) runtype only knows about its `underlying` runtype (`intersectees` for `Intersect`), so if you want to manipulate the underlying one, you have to unwrap first and then rewrap it by a constraint function again, e.g.

```typescript
const myRuntype = Record({
    A: Number,
    B: Number,
}).withConstraint((r) => {
    return r.A > r.B || `A has to be bigger than B`;
});

const myOtherRuntype = myRuntype.underlying.omit("A").withConstraint((r) => {
    if (myRuntype.underlying.pick("A").guard(r)) {
        return r.A > r.B || `A has to be bigger than B`;
    } else {
        return `A has to be present and a number`;
    }
});
```

But I don't see the motivation of this, as the above `myRuntype` and `myOtherRuntype` are essentially the same.

Optionalizing a property can be done by:

```typescript
myRuntype.underlying.omit('A').extend({ A: myRuntype.underlying.fields["A"].optional() })
```

Setting optional properties to be required is, if we have:

```typescript
const myRuntype = Record({
    A: Number.optional(),
    B: Number,
}).withConstraint((r) => {
    if (myRuntype.underlying.pick("A").guard(r)) {
        return r.A > r.B || `A has to be bigger than B`;
    } else {
        return `A has to be present and a number`;
    }
});
```

then:

```typescript
myRuntype.underlying.extend({ A: myRuntype.underlying.fields["A"].underlying })
```

**Comment by woifes** [comment]
Hello and thank you for the response! This is exactly what I am looking for. I achvied to miss the `underlying` property somehow...

Mostly I use it for definitons. If Package A defines a really generic one I want to specialize the definitions in a depending package.

In your first example it is not really the same since I am then able to have a configuration without the "A"s (so it is smaller and less repetitive) and fill up the "A"s incode to later delegate it. But if I need more configuration (like a "C") then it is added automatically.

Thank you very much!
