### ISSUE TITLE
Support for Set type

### ISSUE THREAD

**Issue by atombrenner** [pelotom/runtypes#321]
This a question or a feature wish.

I am using runtypes to validate items from DynamoDB. DynamoDB supports the Set type. So I now have a type  like this

```  typescript

// how to model this type with runtypes?
type Item = {
  a: string
  b: Set<string>
}

const Item = Record({
  a: String,
  b: ???
})

const item: Item = {
  a: 'someString',
  b: new Set(['one', 'two', 'three'])
}

const ddbItem = marshall(item)
Item.check(unmarshall(await getFromDynamoDB(...)))
```

I can't find support for Set or Map types. So in my understanding runtypes only works for data that can be read with `JSON.parse()`. 

Question: Do you think it is possible with reasonable effort to extend runtypes with your own types?
Feature Wish: Support standard Javascript types like Set and Map.

**Comment by yuhr** [comment]
[`InstanceOf`](https://github.com/pelotom/runtypes#instanceof-wrapper) with an additional [guading constraint](https://github.com/pelotom/runtypes#constraint-checking) should do the job for you.

```typescript
const SetString = InstanceOf(Set).withGuard((s): s is Set<string> => [...s].every(String.guard))
const Item = Record({
  a: String,
  b: SetString
})
```

**Comment by atombrenner** [comment]
Thanks :smile:  `withGuard` was the missing link. I was able to create my own generic `SetOf` run type

``` typescript
export const SetOf = <E extends RuntypeBase>(element: E) =>
  InstanceOf(Set).withGuard((x: Set<unknown>): x is Set<Static<typeof element>> => [...x].every(element.guard))
```
