### ISSUE TITLE
[Feature Request] Type Guard for ValidationError 

### ISSUE THREAD

**Issue by vsviridov** [pelotom/runtypes#322]
Provide a helper in the library that acts as a type guard for the Exception thrown from `.check` method.

Recent versions of typescript type all exceptions as `unknown`, and correct handling requires having a typeguard:
```ts

// Would be nice to have this built-in
function isValidationError(ex: unknown): ex is ValidationError {
  return ex instanceof ValidationError
}

try {
  const data = Contract.check(payload);
catch (ex) {
  if(isValidationError(ex)) {
    logger.error(ex.details);
  }
}
```

**Comment by yuhr** [comment]
I think this is already fully covered by `InstanceOf(ValidationError).guard`, with more idiomatic fashion than using a dedicated function.

```typescript
try {
  const data = Contract.check(payload);
catch (ex) {
  if(InstanceOf(ValidationError).guard(ex)) {
    logger.error(ex.details);
  }
}
```

Doesn't this fulfill your needs?

**Comment by vsviridov** [comment]
Yes, this works quite well...
