### ISSUE TITLE
Option to return errors instead of throwing them for performant validation.

### ISSUE THREAD

**Issue by joshi-4** [pelotom/runtypes#325]
Currently runtypes directly throws an error on validation fail. It would be much better to have the option to just return the error as well and throw it. This way it can be used where performance is key, and also be much better custom error handling

**Comment by yuhr** [comment]
What you want is something like below, right?

```typescript
const unknown: unknown = ...

// May throw, as usual
const value: Static<typeof SomeRuntype> = SomeRuntype.check(unknown)

// New API that returns instead of throws
const value: Static<typeof SomeRuntype> | ValidationError = SomeRuntype.test(unknown)
```

**Comment by joshi-4** [comment]
Yes, another way could be to return array of two values i.e [SomeRunType value, ValidationError]. 
Thanks, for the quick response.

**Comment by yuhr** [comment]
My bad, I forgot that there's `validation` API available already:

```typescript
const result: Result<typeof SomeRuntype> = SomeRuntype.validation(unknown)

if (result.success) ...
```

We're sorry this is undocumented, but the shape of the result object is defined here in the code:

<https://github.com/pelotom/runtypes/blob/661c8aceb25d23fa14b6ca1cbffcfef8887a8b8e/src/result.ts#L78>

Is this sufficient for you?

**Comment by joshi-4** [comment]
Yes, I tried it, this solves my case. Thanks
