### ISSUE TITLE
Is it possible to have more than one brand

### ISSUE THREAD

**Issue by cedw032** [pelotom/runtypes#328]
I'm trying to implement some decent number checking and types:

``` typescript
import * as rt from 'runtypes';

export type RealNumber = rt.Static<typeof RealNumber>
export const RealNumber = rt.Number.withConstraint(n => !isNaN(n - n)).withBrand('number.real');

export type Integer = rt.Static<typeof Integer>
export const Integer = RealNumber.withConstraint(n => n % 1 === 0).withBrand('number.integer');
```

Th runtypes themselves look good, but the IntegerType is currently being resolved as never.

My assumption is that this is because there is a phantom brand field or something and that field cannot be two different strings.
If this is the case it would appear that what i am trying to do would not be possible.

I feel that what I am attempting to do here is a valid use case.  When messing around on my own with this sort of things before I have done something like this for managing multi-branding.

``` typescript
type Brand<T extends string> = {
 __brand: {
    [k in T]: T
    }
}

type Real = number & Brand<'number.real'>
type Integer = Real & Brand<'number.integer'>

const integer:Integer = -11 as Integer;
const real:Real = 1 as Real
const integersAreReal: Real = integer;
```

I would love to see something like this implemented.

If there is some way to do this already, if I am doing something wrong, or if you think for some reason this is a bad idea, please let me know.

**Comment by yuhr** [comment]
Thanks, this should be definitely a thing. It wouldn't be hard to implement without breaking change, so I'm going to give it a shot this weekend.

**Comment by cedw032** [comment]
@yuhr - I think I've beaten you to it.
https://github.com/pelotom/runtypes/pull/329

I messed around a little bit changing the reflection but it turned out to be unnecessary.
