### ISSUE TITLE
Creating objects

### ISSUE THREAD

**Issue by danielepolencic** [pelotom/runtypes#35]
I have the following code:

```ts
import { Boolean, Number, String, Literal, Array, Tuple, Record, Union } from 'runtypes';

const Asteroid = Record({
  type: Literal('asteroid'),
  location: Vector,
  mass: Number,
});
```

Is there any _easy_ way to create an object of type `Asteroid`? Ideally, I'd like to use something like:

```ts
Asteroid.create({type: 'asteroid', location: [], mass: 1}); //valid
Asteroid.create({}); // error - the args supplied don't meet the contraints
```

Is this possible? I noticed that none of the examples is creating objects at all.

**Comment by pelotom** [comment]
I’m not sure why you would want this... isn’t `create` just the identity function?

**Comment by pelotom** [comment]
Usually you’d create such an object to immediately pass to some function which requires a specific type. If you want to verify the full structure immediately you can always use type ascription:

```ts
const asteroid: Static<Asteroid> = { ... }
```

**Comment by danielepolencic** [comment]
I'll try that. Thanks!
