### ISSUE TITLE
Provide error meta data

### ISSUE THREAD

**Issue by zaaack** [pelotom/runtypes#39]
It would be great to provide error meta data, something like this:

```js
let error = {
 success: false,
 message: '...',
 path: ['key1', 'key2', ...],
}
```

This can be useful for form validation because we validate the whole form with an object type, but need to show the message in each field.

**Comment by pelotom** [comment]
Yeah, giving more structured error information is definitely a goal. Thanks for making the issue.

**Comment by riston** [comment]
Regarding nested Record types if one of the nested child types is `null` or `undefined` you get really hard to track error `Expected a defined non-null value but was ${typeof x}` https://github.com/pelotom/runtypes/blob/b4f30656cbeb9ec538471bbaa14fc405813a9d54/src/types/record.ts#L16. 
My proposal is to add some sort of statical name(optional) also which could be used for displaying errors:
`const Person = Record({ name: String, age: Number}, 'Person'?);`

**Comment by erkiesken** [comment]
PR #51 partly addresses this with more descriptive error messages with full failing check path in message.

**Comment by Ciantic** [comment]
One way could be to have `NamedRecord('Person', { name: String, age: Number})`, maybe the name could be used elsewhere, e.g. in SQL library that automatically understand the `person` named field as person record or a `personId` as a foreign key.

**Comment by pelotom** [comment]
@Ciantic that's an interesting idea... or perhaps just a general method that let you name any runtype:

```ts
const Foo = Union(
  // ...
).named('Foo');
```

**Comment by elderapo** [comment]
I think it would be a great idea to add `Record.getErrors` and return array of errors ex:
```
[
	{ key: "name", expectedType: "string" receivedType: "number", value: 33 },
	{ key: "age", expectedType: "number" receivedType: "string", value: "Tom" },
]
```
so user will be able to create custom error messages or even create informative error messages in multiple languages.

**Comment by gDelgado14** [comment]
Regarding https://github.com/pelotom/runtypes/pull/51 ... Is the intended behaviour of the MR to describe all the keys which do not adhere to a parser? 

See the example below, where the error is only specifying that `name` is wrong. But `age` is also wrong.

```typescript
const { Number: rtNumber, Record, String: rtString } = require('runtypes')

const r = Record({
  name: rtString,
  age: rtNumber
})

// both fields are wrong
// but runtypes only says that name is wrong
console.log(r.validate({ name: 12, age: 'gio' }))

/*
  { success: false,
  message: 'Expected string, but was number',
  key: 'name' }
*/
```

**Comment by gDelgado14** [comment]
Just realized there's a related / similar issue here https://github.com/pelotom/runtypes/issues/8
