### ISSUE TITLE
Array index

### ISSUE THREAD

**Issue by bbenezech** [pelotom/runtypes#4]
Hi Tom,

How would you model `{[k: string]: any}`, if possible ?

I tried 

```typescript
RT.Record({
    [RT.String as any as string]: RT.String
})
```

It typechecks correctly to `RT.RunType<[x: string]: string;>`, but runtime checks does not work as expected.

**Comment by pelotom** [comment]
Aha, I think we'll need a new Runtype to support that. Something like

```ts
const StrMap = RT.Map(String, String)
```

I'll look into this later today if I get a chance.

**Comment by pelotom** [comment]
Ok, I've added a `Dictionary` runtype for this purpose. You can use it like so:

```ts
RT.Dictionary<T>()         // : Runtype<{ [_: string]: T }>
RT.Dictionary<T>('string') // : Runtype<{ [_: string]: T }>
RT.Dictionary<T>('number') // : Runtype<{ [_: number]: T }>
```

Note that there is no runtime validation performed on the keys or values.
