### ISSUE TITLE
rt.Static<> can't extract static type for Runtype.Record with nested Record ...?

### ISSUE THREAD

**Issue by breathe** [pelotom/runtypes#42]
I'm noticing that I can't seem to correctly extract the static type from Runtype's with nested rt.Record({}).

```
const Example = rt.Record({
  b: rt.Record({
    c: rt.String
  })
});

type StaticExample = rt.Static<typeof Example>;
```

Effective type of StaticExample (as reported by vscode): 
```
type StaticExample = {
    b: any;
}
```

And this produces no type error ...

```
const x: StaticExample = {
  b: ""
};
```

Am I doing something wrong or is this a bug or a known limitation?  I'm using runtypes 2.0.3 with typescript  2.7.2 and this tsconfig:

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./lib",
    "lib": ["es2017", "es2017.object", "esnext.asynciterable"],
    "strict": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "module": "commonjs",
    "esModuleInterop": true,
    "target": "es2015",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "forceConsistentCasingInFileNames": true,
    "strictFunctionTypes": false,
    "noErrorTruncation": true,
    "strictPropertyInitialization": false
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules"]
}
```

**Comment by breathe** [comment]
Update to this:

Actually it appears that the typescript compiler is indeed reporting this as an error -- but not the incremental typescript-server ...

```
file: 'file:///<snip>'
severity: 'Error'
message: 'Type '{ b: string; }' is not assignable to type '{ b: any; }'.
  Types of property 'b' are incompatible.
    Type 'string' is not assignable to type '{ c: string; }'.'
at: '70,7'
source: 'ts'
code: '2322' 
```

The error message is misleading though ...

**Comment by pelotom** [comment]
Hm, that's indeed very odd! I'm seeing the error in vscode as well as on the command-line...

**Comment by gcanti** [comment]
Related https://github.com/Microsoft/TypeScript/issues/14041

**Comment by pelotom** [comment]
>Related Microsoft/TypeScript#14041

Interesting. As @OliverJAsh pointed out, it seems to affect more than just intellisense, maybe the title should be modified?

**Comment by pelotom** [comment]
@gcanti have you found this issue to affect `io-ts`?

**Comment by gcanti** [comment]
@pelotom after some tests looks like my old workaround is still valid (i.e. going through a type alias)

https://github.com/gcanti/io-ts/pull/144

**Comment by darky** [comment]
@pelotom, do you want to fix problem as same way, that gcanti/io-ts#144?
Seems Microsoft/TypeScript#14041 not will be fixed soon

**Comment by pelotom** [comment]
@darky Do you want to submit a PR to fix it? I won't have time to get to it myself in the near term.

**Comment by Ciantic** [comment]
Looks like fix for Microsoft/TypeScript#14041 was merged 3 days ago, not yet sure if it works to fix this bug though.

**Comment by isaac-weisberg** [comment]
And yep it's still not out there to be resolved anywhere soon.

**Comment by yuhr** [comment]
It seems resolved at some point of time. The inferred type of `StaticExample` in the OP is like below in TS 4.2.2:

```ts
type StaticExample = {
    b: {
        c: string;
    };
}
```

So let's close 😄

**Comment by isaac-weisberg** [comment]
POG! Amazing!
