### ISSUE TITLE
Checking objects on values only?

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#43]
Is there any runtypes equivalent of following type definition? I don't want to specify key strings but check if the type of their values is string. 
```typescript
type Json = { [key: string]: string };
```

**Comment by pelotom** [comment]
Sounds like you want a [Dictionary](https://github.com/pelotom/runtypes/blob/master/src/types/dictionary.ts).

**Comment by yuhr** [comment]
That's it, thanks. I've found the space-game example you added 😭 I love runtypes' beautiful API.

**Comment by pelotom** [comment]
Thanks for the kind words!
