### ISSUE TITLE
Symbol type

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#44]
Can you add checker for Symbol type?

**Comment by pelotom** [comment]
Would `InstanceOf(Symbol)` do the job?

**Comment by yuhr** [comment]
TS says:
```
Argument of type 'SymbolConstructor' is not assignable to parameter of type 'Constructor<{}>'.
  Type 'SymbolConstructor' provides no match for the signature 'new (...args: any[]): {}'.
```
And cannot compile 😢 Please describe how to use it

**Comment by pelotom** [comment]
Ah, looks like `Symbol` is treated as a special case (which isn't too surprising). A custom runtype for `Symbol` is probably in order.

**Comment by yuhr** [comment]
Btw without `as` import it'll shadow the original `Symbol` identifier and disable static methods such as `Symbol.for` and `Symbol.keyFor` ... this is not specific to `Symbol`. Is there any way to "merge" the original methods into custom runtype? Is it possible?

**Comment by pelotom** [comment]
> Is there any way to "merge" the original methods into custom runtype? Is it possible?

I'm not thrilled about that idea... the runtype object serves a very different purpose and shouldn't be conflated. Using `import * as rt` for example is the right way to disambiguate where needed.

**Comment by yuhr** [comment]
That's right indeed, sorry for the rough question. Thanks a lot 🌟
