### ISSUE TITLE
Incorrect generic type constraint for interface Record?

### ISSUE THREAD

**Issue by alexdslva** [pelotom/runtypes#46]
Hi,
When I open `record.ts` in Visual Studio Code with TypeScript 2.8.1, the following error is shown:

![image](https://user-images.githubusercontent.com/5452404/38460403-5f258a0e-3ab9-11e8-9264-1036887c5688.png)

Current definition:
```typescript
export interface Record<O extends { [_ in never]: Runtype }>
  extends Runtype<{ [K in keyof O]: Static<O[K]> }> {
  tag: 'record';
  fields: O;
}
```
Isn't the following more appropriate? If not, I would appreciate if you explain me why! I don't understand the current constraint for the generic type.

```typescript
export interface Record<O extends { [_: string]: Runtype }> // [_: string] instead of [_ in never]
  extends Runtype<{ [K in keyof O]: Static<O[K]> }> {
  tag: 'record';
  fields: O;
}
```
Thank you in advance.

**Comment by pelotom** [comment]
Fixed by #49.
