### ISSUE TITLE
`check` should be able to return branded type

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#54]
The `check` method of a runtype with constraint returns a value of the type without constraint, so sometimes I need to use branded types like this:

```typescript
const A = String.withConstraint(x => x === 'a');
type A = Static<typeof A> & { __brandA: any };
const x: string = 'a';
const a: A = A.check(x); // Type 'string' is not assignable to type 'A'.
const a: A = A.check(x) as A; // OK but looks verbose
```

Then maybe it's good that `check` or some another (defined anew?) method can return some user defined type, for example:

```typescript
let A = String.withConstraint(x => x === 'a');
type A = Static<typeof A> & { __brandA: any };
A = Brand<A>(A);
const x: string = 'a';
const a: A = A.verify(x); // Should be OK
```

I think this is still ugly but absolutely better than doing `as A` whenever `A.check(x)`. 

How do you think?

**Comment by pelotom** [comment]
It seems like what you want is the ability to optionally "name" a constraint, e.g.

```ts
const A = String.withConstraint('A', x => x === 'a');
```

And then have

```ts
type A = Static<typeof A>; // === string & { _constraintName: 'A' }
```

Does that make sense?

**Comment by yuhr** [comment]
Yes it'll work but I said "constraints" as just an instance, sorry. It won't do a thing when one can't provide any constraints for two `String` runtypes but need discriminate them, for example:

```typescript
const USEnglishDescription = String;
const UKEnglishDescription = String;
```

And also not only for `String`... many cases. So I think it's better to define a new function something like `Brand` I described above, or method like `String.Brand('A')`.

**Comment by pelotom** [comment]
Ok, would you be interested in making a PR?

**Comment by yuhr** [comment]
Yes, I'm starting to implement this.
