### ISSUE TITLE
Support for optional properties

### ISSUE THREAD

**Issue by chris-pardy** [pelotom/runtypes#60]
Currently the Record type's validation verifies that a property exists before checking their types. This causes problems when some properties on a Record should be optional.

Current Behavior:
```
Record({
 id: String,
 name: Union(Undefined,String)
}).validate({id: '1234'}).success === false
```
Expected Behavior:
```
Record({
 id: String,
 name: Union(Undefined,String)
}).validate({id: '1234'}).success === true
```
Also acceptable:
```
Record({
 id: String,
 name: Optional(String)
}).validate({id: '1234'}).success === true
```

Current Workaround:
```
Intersect(
  Record({
    id: String,
  }),
 Partial({
   name: String
 })
).validate({id: '1234'}).success === true
```

**Comment by gscscnd** [comment]
It seems that workaround is the correct solution: #40.

**Comment by chris-pardy** [comment]
@gscscnd / @pelotom I would disagree that it's the "correct solution" even if it does work. Specifically the following seems really wrong:
```
const nameAndId = Record({
  id: String,
  name: Union(Undefined, String)
});

const input = {
  id: '1234',
  name: undefined
};

nameAndId.validate(input).success === true; // true
nameAndId.validate(JSON.parse(JSON.stringify(input))).success === false;
```
This basically means that there's no component in runtypes that can correctly validate calls that go through JSON serialization. If that's not a core use-case for this library I'm not sure what is.

**Comment by chris-pardy** [comment]
@pelotom I put 3 suggestions in this issue already, but let me lay them out again.

1.  Don't check that a key exists when validating a record - a key that doesn't exist, or one that contains the value undefined are semantically the same in most javascript / typescript code. (This is a one line change in the Record file, I can open a PR for this if you'd like.)
2. Add an additional utility for "Optional" that would effectively do the same thing as Union(Undefined,....) but that would allow Record to skip the key existence check.
3. Add a new type `Struct`(?) that would have the logic of option 1.

* Option 1 - Probably the cleanest solution, it's a simple change in the code and a few new test cases. Technically the behavior we're changing was undocumented, and not covered by test cases so it should be a non-breaking change, although strictly speaking you could consider it a backwards incompatible change.
* Option 2 - Kinda sucks, it matches closer to how Typescript works having a different way to annotate a property as optional, but it's weird that you'd be having 2 ways to do the same thing, but with different meanings depending on their use. The nice thing is that this is fully backwards compatible.
* Option 3 - Fine, backwards compatible, easy to use, but do we really need a new type for this?

**Comment by chris-pardy** [comment]
@pelotom PR #61 is what I described above as "Option 1"
