### ISSUE TITLE
Map runtypes to JSON schema

### ISSUE THREAD

**Issue by sinclairzx81** [pelotom/runtypes#62]
Hi, Just reaching out to get some thoughts on potentially generating JSONschema from runtypes type representations, and if such a library exists to achieve this.

Just for some background, we currently have a project where we have several dozen json endpoints and for each endpoint, we have a `TRequest` and `TResponse` TypeScript type as well as a corresponding JSONSchema type (for both request, response). As you can imagine, this is quite the duplication, and we feel this duplication could potentially be removed with the use of `runtypes`.

One of our considerations however is we do like the idea of publishing `TRequest` / `TResponse` schema information to our clients (similar to WSDL). In fact our preference is to publish JSONSchema as a standard JSON schematic (analogous to XSD, WSDL) but to do so, we would need to map runtypes to JSONSchema somehow.

So wondering if there is functionality to do something similar to the following....

```typescript
const Asteroid = Record({
  type: Literal('asteroid'),
  location: Vector,
  mass: Number,
});
// runtypes representation
// Asteroid = { tag: 'record',
//  fields:
//   { type:
//      { tag: 'literal',
//        value: 'asteroid',
//        check: [Function],

const AsteroidSchema = Asteroid.toJsonSchema()
// json schema representation
// AsteroidSchema = {
//     type: 'object',
//     properties: {
//       type: {type: 'string'},
//       location: {
//          x: { type: 'number'},
//          y: { type: 'number'},
//       ...
```
From this, we would be able to integrate runtypes with our existing json schema validators (we are currently using the `ajv` json schema validator configured for draft 6).

Any information you can provide would be great.

Kind Regards
Sinclair

**Comment by pelotom** [comment]
@sinclairzx81 I would think it should be fairly straightforward to write a `toJsonSchema()` function against the `Reflect` API. See the implementation of [show()](https://github.com/pelotom/runtypes/blob/master/src/show.ts) for an example of how to do this. Let me know if you have any questions about it!

**Comment by sinclairzx81** [comment]
@pelotom Awesome, thanks for the quick response, that's great :) Will certainly take a look at this. With respect to `union` and `intersect` i think these could be expressed by way of `anyOf` and `allOf`, with perhaps the only things not directly mappable being the `function`, `always`, `never`, `instanceof`, `void`, with `record` and `partial` mapping to `object` and dictionaries being quite interesting, but there is certainly enough here for us to go on. Will be really interesting to map things across.

Happy to report progress and findings as we explore a bit more within this thread, runtime type validation in typescript tagged with reflectable operational RPC is such a win for JavaScript, so thanks so for your great work !

Regards
S

**Comment by pelotom** [comment]
Great, happy to advise if you have questions!

**Comment by sinclairzx81** [comment]
Hi, hope you are doing well :) 

Have done some provisional work mapping things over to JSON schema, have a couple question related to `optional` / `readonly` type modifiers. Perhaps something along the lines of.

```typescript
const Asteroid = Record({
  type: Literal('asteroid'),
  location: Readonly(Vector),
  mass: Optional(Number),
});
```
which might statically resolve to.
```typescript
type Asteriod = {
  type: "asteriod",
  readonly location: Vector,
  mass?: number
}
```
which could resolve to the following schema.
```json
{
   "type": "object",
   "properties": {
      "type": {  "type": "string", "pattern": "asteroid" },
      "location": { 
          "type": "object", 
          "properties": {
              "x": { "type": "number"}, 
              "y": {"type": "number"} 
           },
           "mass": { "type": "number" }
        },
       "required": [
          "type", "location" 
       ]
    }
}
```
where `mass` is omitted on the `required` array on `object` and `readonly` only really meaningful to the static resolution.

I had a look through the runtypes source looking for a means to modify the `record` type modifier, but couldn't find anything specific.

I submitted an issue for statically mapping `readonly` and `optional` modifiers on the TS repo a few weeks back found [here](https://github.com/Microsoft/TypeScript/issues/24951). Would a feature like this be an enhancement on the existing `runtypes` library or is functionality like this existing already?

**Comment by pelotom** [comment]
> ```typescript
> const Asteroid = Record({
>   type: Literal('asteroid'),
>   location: Readonly(Vector),
>   mass: Optional(Number),
> });
> ```
> which might statically resolve to.
> ```typescript
> type Asteriod = {
>   type: "asteriod",
>   readonly location: Vector,
>   mass?: number
> }
> ```

Perhaps something like this is possible with conditional types, but I haven't had time to look into it. You're welcome to give it a try in a PR!

**Comment by sinclairzx81** [comment]
@amonks nice thanks. I sorta ended up rolling my own thing in the end though with [typebox](https://github.com/sinclairzx81/typebox). Had some trouble mapping `optional` types and a few other things using runtypes, so opted for a plain old json schema builder + static resolution using typescript type mapping.

Will mark this issue as closed.

**Comment by cdaringe** [comment]
@amonks, your URL for runtype-schema is a 404. still have it?

**Comment by cdaringe** [comment]
I've created such a tool: https://github.com/cdaringe/runtypes-to-jsonschema

pretty basic so far (not JSONSchema feature complete, such as no use of definitions/refs/requiredFields), but the core components work, and we'll make it mo better over time
