### ISSUE TITLE
How to represent 'any' types? 

### ISSUE THREAD

**Issue by ryardley** [pelotom/runtypes#63]
I am trying to convert an existing codebase to use runtypes.

However I am struggling to work out how to represent the `arguments` key here with a typescript `any` type:

```typescript
export type Description = {
  name: string;
  type: 'fanout' | 'topic' | 'direct';
  durable?: boolean;
  internal?: boolean;
  autoDelete?: boolean;
  alternateExchange?: string;
  arguments?: any;
};
```

So far I have this:

```typescript
Record({
  name: String,
  type: Union(Literal('fanout'), Literal('topic'), Literal('direct'))
}).And(
  Partial({
    alternateExchange: String,
    autoDelete: Boolean,
    durable: Boolean,
    internal: Boolean
    //arguments: Any // Any is not exported from runtypes
  })
)
```

Runtime type checking works:

```typescript
Description.check({
  name:'foo',
  type: 'fanout',
  arguments: {
    ding:'pop'
  }
}); // no errors
```

However the following causes type errors in editor: 

```typescript
const myDescription: Static<typeof Description> ={
  name:'foo',
  type: 'fanout',
  arguments: { // shows error 
    ding:'pop'
  }
}
```
The error is 

`Object literal may only specify known properties, and 'arguments' does not exist in type...`

How do I infer this property should be `any`?

**Comment by pelotom** [comment]
Have you taken a look at the `Always` type? (It will most likely be renamed to `Unknown` soon as it corresponds to the new `unknown` type in TS 3.0, but will remain as an alias).

**Comment by Feofilakt** [comment]
And how to respresent "any" type now?

**Comment by yuhr** [comment]
@Feofilakt What are actual needs of `Any` runtype? You can cast `unknown as any` when you need it, so there's no reason to provide it as another runtype separatedly from `Unknown`.

**Comment by Feofilakt** [comment]
@yuhr, Yes, it is exactly what I did after not founding a way to represent "any" type

**Comment by yuhr** [comment]
Hmm, both [`zod`](https://github.com/colinhacks/zod/blob/1.11/README.md#primitives) and [`rulr`](https://github.com/ryansmith94/rulr/blob/v8.0.0/src/valueRules/any/readme.md) have `any` as a validator object separatedly from `unknown`, while [`io-ts`](https://github.com/gcanti/io-ts/blob/2.2.16/docs/modules/index.ts.md#any) deprecates it in favor of `unknown`. I'd go for the direction of `io-ts`. If we provide `Any` runtype, say you have `const SomeString = Any // FIXME: temporary` elsewhere and forgot it, then `const s: string = SomeString.check(...)` would silently undermine type-safety of your variable `s` without any warning from TS. Obviously this is not a thing `runtypes` is supposed to do. So again, if you really have to get a runtype without any validation with its static type resulting in `any`, we have to ask you to use something like `Unknown.check(...) as any`.
