### ISSUE TITLE
Regression on the "More descriptive errors" feature

### ISSUE THREAD

**Issue by epeli** [pelotom/runtypes#64]
It seems that #51 has regressed in later versions.

In 2.0.5 I get error messages like

	Expected restEndpoint to be string

but in 2.1.6 they are just

	Expected string, but was undefined

Reproduce with

```ts
const Options = rt.Record({
    restEndpoint: rt.String,
    userId: rt.String,
});
Options.check({userId: ""});
```

**Comment by pelotom** [comment]
The information about which key is missing in the record can be obtained from the `key` property on the error object:

```ts
  try {
    Options.check({userId: ""});
  } catch ({ message, key }) {
    console.log(`${key}: ${message}`);
  }
```

**Comment by epeli** [comment]
Thanks!
