### ISSUE TITLE
[Support] How to deal with enums and types defined by external libraries?

### ISSUE THREAD

**Issue by wujekbogdan** [pelotom/runtypes#66]
I have the following TypeScript code

``` typescript
import * as admin from "firebase-admin";

export enum Parser {
  STANDARD = "standard",
  FIVE_FILTERS = "fiveFilters",
}

export enum Status {
  DRAFT = "draft",
  PUBLISHED = "published",
}

export interface IWriter {
  feedName: string;
  writerRef: admin.firestore.DocumentReference;
}

export interface IEntryDocument {
  cronExpression: string;
  forceTeams: boolean;
  forceWriters: boolean;
  id: string;
  name: string;
  parser: Parser;
  status: Status;
  url: string;
  writers: IWriter[];
}
```

I need to validate the data that comes from the DB so I need to perform validation based on the  `IEntryDocument` interface typings.

I started on converting these interfaces into runtypes format but I'm stuck with enums and external libraries' types.

This is where I reached so far:

``` typescript
import * as admin from "firebase-admin";
import {Boolean, String, Static, Array, Record} from "runtypes";

export enum Parser {
  STANDARD = "standard",
  FIVE_FILTERS = "fiveFilters",
}

export enum Status {
  DRAFT = "draft",
  PUBLISHED = "published",
}

const Writer = Record({
  feedName: String,
  // writerRef: admin.firestore.DocumentReference,
});

export interface IWriter {
  feedName: string;
  writerRef: admin.firestore.DocumentReference;
}

const EntryDocument = Record({
  cronExpression: String,
  forceTeams: Boolean,
  forceWriters: Boolean,
  id: String,
  name: String,
  // parser: Parser,
  // status: Status,
  url: String,
  writers: Array(Writer),
});

export interface IWriter extends Static<typeof Writer> {}
export interface IEntryDocument extends Static<typeof EntryDocument> {}
```

Have a look at the lines that are commented out. I'm stuck with 2 issues:

1. I don't know what to do with `admin.firestore.DocumentReference`
2. I don't know how to deal with `Parser`  and `Status` enums

**Comment by hmil** [comment]
I would leave `admin.firestore.DocumentReference` as an `Unknown` unless you know what's inside this type and you are able to easily map it to a runtype of your own.
Then I'd treat the enums like string unions (eg.  `parser: Union(String('standard'), String('fiveFilters'))`)

**Comment by tvald** [comment]
For a complex external type `Complex`, perhaps a new runtype `Unsafe` could be added that always validates, just like `Unknown`, but also asserts for the compiler that the type is `Complex`. 

```ts
const complex = Unsafe<Complex>();
// Static<typeof complex> === Complex
```

This at least enables the compiler to check the type wherever possible, and should be no more unsafe than the type assertion required to use a value validated by `Unknown`.

It might also be worth accepting a "light" validator function as a parameter:

```ts
const readableStream = Unsafe<NodeJS.ReadableStream>(x => 'read' in x);
```

**Comment by tvald** [comment]
Actually, this is possible right now with a very reasonable syntax:
```ts
const complex = Unknown as Runtype<Complex>;
```

The "light" validator runtype might still be an interesting path to enable some modicum of runtime safety.

**Comment by tvald** [comment]
The "light" validator is possible like so:
```
const complex = Unknown.withConstraint(x => 'foo' in x) as Runtype<Complex>;
```

**Comment by pelotom** [comment]
There's [a feature in the works](https://github.com/pelotom/runtypes/pull/78) to make `Constraint` able to change the static type associated with a runtype. Just needs documentation and it will be ready to merge (*nudge @justingrant*).

**Comment by justingrant** [comment]
Sorry @pelotom and @tvald for lagging on this. Will try to get it out next week.  Have been knee-deep in other stuff for the last few weeks.

**Comment by pelotom** [comment]
@justingrant no worries, just wanted to make sure you knew your work will be appreciated 😉

**Comment by pelotom** [comment]
#78 has been merged and released in `runtypes@4.0.0`, so this should be solved now.

**Comment by ronanquillevere** [comment]
For parser I would use

```typscript
Union(
    Literal(Parser. STANDARD),
    Literal(Parser. FIVE_FILTERS)
  )
```

**Comment by dforsber** [comment]
> For parser I would use
> 
> ```js
> Union(
>     Literal(Parser.STANDARD),
>     Literal(Parser.FIVE_FILTERS)
>   )
> ```

Is there a way to create that Union programmatically based on the entries in the `enum`? As if you update the enum and forget to update the `Union`..

**Comment by xavichoudev** [comment]
> > For parser I would use
> > ```js
> > Union(
> >     Literal(Parser.STANDARD),
> >     Literal(Parser.FIVE_FILTERS)
> >   )
> > ```
> 
> Is there a way to create that Union programmatically based on the entries in the `enum`? As if you update the enum and forget to update the `Union`..

Warning Union seems to be limited to max 20 elements.

**Comment by marlonjan** [comment]
If you want to (or have to) keep the enum, this snippet might be useful:

```typescript
const runtypeFromEnum = <EnumType>(theEnum: Record<string, EnumType>): rt.Runtype<EnumType> => {
    const values = Object.values<unknown>(theEnum);
    const isEnumValue = (input: unknown): input is EnumType => values.includes(input);
    const errorMessage = (input: unknown): string =>
        `Failed constraint check. Expected one of ${JSON.stringify(values)}, but received ${JSON.stringify(input)}`;
    return rt.Unknown.withConstraint<EnumType>((object: any) => isEnumValue(object) || errorMessage(object));
};
```

Usage:
```typescript
enum Parser {
    STANDARD = 'standard',
    FIVE_FILTERS = 'fiveFilters',
}

const ParserRuntype = runtypeFromEnum(Parser);

const p1: Parser = ParserRuntype.check(Parser.STANDARD); // ok
const p2: Parser = ParserRuntype.check('standard');      // ok
const p3: Parser = ParserRuntype.check('standarddd');    // error

```

(Inspired by @pelotom's replies here and answers to a very [similar question](https://github.com/gcanti/io-ts/issues/216#issuecomment-621588750) in the io-ts issues.)

**Comment by Mearman** [comment]
> If you want to (or have to) keep the enum, this snippet might be useful:
> 
> ```ts
> import * as rt from 'runtypes';
> 
> const runtypeFromEnum = <EnumType>(theEnum: Record<string, EnumType>): rt.Runtype<EnumType> => {
>     const values = Object.values<unknown>(theEnum);
>     const isEnumValue = (input: unknown): input is EnumType => values.includes(input);
>     const errorMessage = (input: unknown): string =>
>         `Failed constraint check. Expected one of ${JSON.stringify(values)}, but received ${JSON.stringify(input)}`;
>     return rt.Unknown.withConstraint<EnumType>((object: any) => isEnumValue(object) || errorMessage(object));
> };
> ```
> 
> Usage:
> 
> ```ts
> enum Parser {
>     STANDARD = 'standard',
>     FIVE_FILTERS = 'fiveFilters',
> }
> 
> const ParserRuntype = runtypeFromEnum(Parser);
> 
> const p1: Parser = ParserRuntype.check(Parser.STANDARD); // ok
> const p2: Parser = ParserRuntype.check('standard');      // ok
> const p3: Parser = ParserRuntype.check('standarddd');    // error
> ```
> 
> (Inspired by @pelotom's replies here and answers to a very [similar question](https://github.com/gcanti/io-ts/issues/216#issuecomment-621588750) in the io-ts issues.)

@marlonjan I understand the usage but I'm not entirely sure what the value of the `input is EnumType` is in the declaration of `isEnumValue`

**Comment by schulmacher** [comment]
To get a better error message, you can defined the `{ name }` property for `withConstraint`. Otherwise the error message says "_Failed constraint check for **unknown**_" or for unions "_Expected **unknown** | **unknown**_".


```ts
export const RuntypeEnum = <EnumType>(theEnum: Record<string, EnumType>, name: string): RT.Runtype<EnumType> => {
  const values = Object.values<unknown>(theEnum);
  const isEnumValue = (input: unknown): input is EnumType => values.includes(input);
  const errorMessage = (input: unknown): string =>
    `Expected one of ${JSON.stringify(values)}, but received ${JSON.stringify(input)}`;

  return RT.Unknown.withConstraint<EnumType>((object) => isEnumValue(object) || errorMessage(object), { name });
};
```

<details>

```ts
enum MyEnum {
  VALUE_1 = 'value1',
  VALUE_2 = 'value2',
}

enum MyEnum2 {
  VALUE_1 = 'value1',
  VALUE_3 = 'value3',
}

const MyEnumCombined = {
  ...MyEnum,
  ...MyEnum2,
} as const;

expect(RuntypeEnum(MyEnum, 'MyEnum').validate('Wronk')).toEqual({
  success: false,
  code: 'CONSTRAINT_FAILED',
  message: 'Failed constraint check for MyEnum: Expected one of ["value1","value2"], but received "Wronk"',
});
expect(RuntypeEnum(MyEnum, 'MyEnum').Or(RuntypeEnum(MyEnum2, 'MyEnum2')).validate('Wronk')).toEqual({
  code: 'TYPE_INCORRECT',
  message: 'Expected MyEnum | MyEnum2, but was string',
  success: false,
});
expect(RuntypeEnum(MyEnumCombined, 'MyEnumCombined').validate('Wronk')).toEqual({
  code: 'CONSTRAINT_FAILED',
  message:
    'Failed constraint check for MyEnumCombined: Expected one of ["value1","value2","value3"], but received "Wronk"',
  success: false,
});
```

<summary>
Test cases
</summary>
</details>
