### ISSUE TITLE
Error message change with release v2.1.6

### ISSUE THREAD

**Issue by riston** [pelotom/runtypes#68]
Noticed that with the latest version v2.1.6 the error message format has been changed (https://github.com/pelotom/runtypes/pull/61/files#diff-92c6b06e4d1db78667de9db352d5cc7bL30) and doesn't contain `key` in the error message. It would be still really useful to have the key name also in error message.

**Comment by yuhr** [comment]
Closing as it's stale. `key` in result objects is superseded by `details` property in v6.
