### ISSUE TITLE
`check()` returns any for nested types

### ISSUE THREAD

**Issue by xealot** [pelotom/runtypes#69]
In this simple example:

```ts
const SubValue = Record({
    a: Number,
});

const ParentValue = Record({
    v: Array(SubValue),
});

const pv = ParentValue.check({});
```

The type returns from `check()` is `{v: any[]}`. But when I look at the type of ParentValue it's fully realized. What am I missing?

**Comment by pelotom** [comment]
Duplicate of #42?

**Comment by xealot** [comment]
Indeed it is, don't know why I couldn't find this earlier. Thanks for the pointer.
