### ISSUE TITLE
Automatic argument checking

### ISSUE THREAD

**Issue by yuhr** [pelotom/runtypes#70]
Sometimes we need type-check multiples of multiple parameters which are passed from the external world i.e. there're some callbacks to implement, and appending type-checking code for each param to every one of their function bodies is kind of painful. In such case I write a decorator which reduces keypresses more or less and makes functions' logic innate-looking, for example,

```typescript
@checked(Runtype1, Runtype2, Runtype3)
method(param1: Static1, param2: Static2, param3: Static3) {
  ...
}
```

instead of

```typescript
method(param1: Static1, param2: Static2, param3: Static3) {
  Runtype1.check(param1)
  Runtype2.check(param2)
  Runtype3.check(param3)
  ...
}
 ```

How do you think about adding this feature to your library?

**Comment by pelotom** [comment]
This sounds like the purpose of [contracts](
https://github.com/pelotom/runtypes#function-contracts), although I haven’t tried using them as a decorator. If there’s something that we could do to make them more idiomatic for that purpose I’d be open to it.

**Comment by yuhr** [comment]
Yes of course, so contracts look like:

```typescript
method = Contract(Runtype1, Runtype2, Runtype3)
  .enforce((param1: Static1, param2: Static2, param3: Static3) => {
    ...
  })
```

However, my understanding is if one wants to write a single function then a contract should fit (and calling an external function may also fits), but for implementing class methods, usually there's no need to type-check the returning value as it is already in the internal type-safe world, that is, returning a member, a return value from another method, or something else which is try-catched or guarded within their mechanism.

And another advantage is that we can skip trailing params:

```typescript
@checked(Runtype1, Runtype2)
method(param1: Static1, param2: Static2, param3: any) {
  ...
}
```

Also we can utilise parameter decorators for marking which params shall be type-checked:

```typescript
@checked(Runtype1, Runtype3)
method(@check param1: Static1, param2: any, @check param3: Static3) {
  ...
}
```
or kind of
```typescript
@checked
method(@check(Runtype1) param1: Static1, param2: any, @check(Runtype3) param3: Static3) {
  ...
}
```

We use `Always` or other primitives in the case of contracts, but it's somewhat verbose I think.
