### ISSUE TITLE
Related library: rest.ts

### ISSUE THREAD

**Issue by hmil** [pelotom/runtypes#73]
Hi @pelotom ,

I'm developing a module to bridge the safety gap across HTTP APIs, with first-class support for runtypes.

The module is called [rest.ts](https://github.com/hmil/rest.ts) and it lets you write API definitions which you can bind to client and servers in order to benefit from type safety on both ends of the API.  
When used with runtypes, the server-side module validates all incoming data automatically.

I thought you might like this module because basically it is to HTTP APIs what runtypes is to basic types. It's almost like a natural extension of your work.

Please give it a try if you can and let me know what you think of it, and if you think it's worthy of the "related libraries" section of the readme.

**Comment by pelotom** [comment]
Looks very cool, I will definitely add it to the `README`!
