### ISSUE TITLE
Static type not recognizing that a field is nullable

### ISSUE THREAD

**Issue by gDelgado14** [pelotom/runtypes#76]
Hi, first of all. Thanks for this awesome package! I've noticed that typescript is not recognizing that a `Record` field is `.Or(Null)`. Instead typescript is inferring it to be non-null. 

Is this expected behaviour? 

See the screenshot below:

<img width="566" alt="screen shot 2019-02-17 at 10 19 48 am" src="https://user-images.githubusercontent.com/10621548/52915098-e97c4300-329d-11e9-99bb-46b199ffd5a7.png">

**Comment by pelotom** [comment]
Do you have `"strictNullChecks": true` in your `tsconfig.json`? TypeScript collapses the types `T | null` and `T | undefined` into `T` when unless this flag is enabled.

**Comment by gDelgado14** [comment]
That resolved it! Thank you.
