### ISSUE TITLE
Creating object map from union of literals

### ISSUE THREAD

**Issue by matomesc** [pelotom/runtypes#79]
Given the following union:
```
const TimeUnit = Union(
  Literal('minute'),
  Literal('hour'),
  Literal('day')
);
```
I'd like to get an object map with each key having the literal value:
```
const TimeUnitMap = {
  minute: 'minute',
  hour: 'hour',
  day: 'day',
}
```
What I'm doing right now is using this function:
```
function getObjectMap<T extends string>(union: { alternatives: Literal<T>[] }) {
  return union.alternatives.reduce((acc, val) => {
    acc[val.value] = val.value;
    return acc;
  }, {} as Record<T, T>)
}
```
It works but the type of each value is `'minute' | 'hour' | 'day'`. I would like the type of the value to be the literal value, so type of `TimeUnitMap.minute` is `'minute'`, similar to a string enum.

Is this possible? The only way I can think of doing it is having the object created first and then the union from the object's keys.

**Comment by pelotom** [comment]
For any type which is a union of string literals,

```ts
type X = 'a' | 'b' | 'c' | ...;
```

you can get the corresponding record type

```ts
type Y = {
  a: 'a';
  b: 'b';
  c: 'c';
  ...
};
```

by defining

```ts
type Y = { [K in X]: K extends X ? K : never };
```

So you just want to make that the return type of `getObjectMap`:

```ts
function getObjectMap<T extends string>(union: { alternatives: RT.Literal<T>[] }) {
  return union.alternatives.reduce((acc, val) => {
    // not totally sure why the cast is necessary here
    (acc as any)[val.value] = val.value;
    return acc;
  }, {} as { [K in T]: K extends T ? K : never });
}
```

**Comment by matomesc** [comment]
Cheers that works!
