### ISSUE TITLE
The Void runtype doesn't match the typescript void type

### ISSUE THREAD

**Issue by googol** [pelotom/runtypes#81]
Typescript considers `void` to be equal to `undefined`, not `undefined | null`.

Test:
```ts
const x: string | void = null; // Type 'null' is not assignable to type 'string | void'.
```

This is of course because `void` exists to mark that a function should not have a `return` statement, and the return value of a function without a return statement is `undefined`.

Why is the Void runtype implemented differently?

**Comment by pelotom** [comment]
`void` is a weird type which is treated as a special case within TypeScript. Technically, any value could be lurking within a `void`. E.g.

```ts
type VoidMaker = () => void;
const f: VoidMaker = () => 42; // no type error
const x = f(); // x: void and x === 42
```

I agree that limiting to `undefined | null` doesn't make sense, but neither does limiting to `undefined`, really. If anything, it's effectively equivalent to `unknown`; we really can't say anything about it. Probably there shouldn't be a `Void` runtype at all; I don't think I understood its semantics when I first implemented it. Now that it's here, perhaps it should just be made an alias to `Unknown`?

**Comment by googol** [comment]
Yeah making it an alias of `Unknown` would make sense, possibly also marking it `@deprecated`

**Comment by pelotom** [comment]
Happy to accept a PR to that effect.
