### ISSUE TITLE
Type 'BooleanConstructor' is missing properties from type 'Runtype<unknown>'

### ISSUE THREAD

**Issue by gavinwahl** [pelotom/runtypes#85]
With this code, on 3.2.0:

```
import { Record, Boolean } from 'runtypes';

const Test = Record({
  foo:  Boolean,
});
```

I get this error: `Type error: Type 'BooleanConstructor' is missing the following properties from type 'Runtype<unknown>': check, validate, guard, Or, and 5 more.  TS2740`

**Comment by pelotom** [comment]
Hm, the code as you've written it works fine for me. Are you sure you imported `Boolean`? The error message you've given makes it seems as if you didn't; I get that error with this code:

```ts
import { Record } from 'runtypes';

const Test = Record({
  foo:  Boolean,
});
```

**Comment by gavinwahl** [comment]
Yep, I missed the import and it was using the built-in Boolean :facepalm: Thanks
