### ISSUE TITLE
Tuples length

### ISSUE THREAD

**Issue by Hypercubed** [pelotom/runtypes#94]
Looks like `Tuples` match for arrays with a length >= to the component length?  Shouldn't tuples need to match the length exactly?  See https://github.com/pelotom/runtypes/blob/master/src/types/tuple.ts#L235 .

Also, any reason not to have a Tuples of length 0 and 1?  Since arrays don't have a constraint on length it seems like a Tuples is better for these cases.

**Comment by pelotom** [comment]
> Looks like `Tuples` match for arrays with a length >= to the component length? Shouldn't tuples need to match the length exactly? See [/src/types/tuple.ts@`master`#L235](https://github.com/pelotom/runtypes/blob/master/src/types/tuple.ts#L235) [](/pelotom/runtypes/blob/HEAD@{2019-07-05T02:49:51Z}/src/types/tuple.ts#L235) .

Yes, you're right. Care to open a PR to fix it?

> Also, any reason not to have a Tuples of length 0 and 1? Since arrays don't have a constraint on length it seems like a Tuples is better for these cases.

There are tuples of length 1 (although I've never had occasion to use them):

https://github.com/pelotom/runtypes/blob/3385f5e3a3e4d206029c565533d13b3f8c8619b1/src/types/tuple.ts#L6

Likewise tuples of length 0 don't seem very useful but I'm not opposed to adding them for completeness.

**Comment by yuhr** [comment]
Seems like it's already resolved by #124. Closing.
