### ISSUE TITLE
Using runtypes as a library

### ISSUE THREAD

**Issue by lkostrowski** [pelotom/runtypes#97]
Hi

I find great usage of runtypes as an external library for multi-packages created with typescript.
For example I write frontend in React and backend in Nest.

Now I'd like to extract my interfaces (wich I have, but using `Static<>`) to separate package to use it as npm library (either local linking, private repo etc). 

I tried to extract it to separate Lerna package, but CRA isn't able to resolve files from outside `src`, also Typescript paths are disabled.

So I'd like to have a library created only with RunTypes and `Static<>` types resolved from RunTypes and import them in my packages.

Any idea how to achieve this? Linking `index.d.ts` with interfaces only should work, but RunTypes has to be compiled first so I can import it. Will compilation break types in this case?

**Comment by pelotom** [comment]
I'm honestly not sure what the issue is. https://github.com/alexjoverm/typescript-library-starter might be a good starting point, then just export whatever runtypes and static types you want from `index.ts` and everything should work...

**Comment by lkostrowski** [comment]
Yea... I just struggle possibly with config.
Using typescript-library-started I have
`Error: 'Record' is not exported by node_modules/runtypes/lib/index.js`

But maybe I just have dig deeper into TS building
