### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by artalar** [pelotom/runtypes#98]
Can u suggest in the docs some naming conventions for semantic separation of types and runtypes?

For example, I need to describe the axios response. How can I name the instance of `Runtype<AxiosResponse>`?
```ts
import { AxiosResponse } from 'axios';

const AxiosResponseRuntype: Runtype<AxiosResponse> = T.Record({
    data: T.Unknown,
    status: T.Number,
    statusText: T.String,
    headers: T.Unknown,
    config: T.Unknown, // AxiosRequestConfig,
    request: T.Unknown, // optional
});
```

**Comment by pelotom** [comment]
I usually just name them the same as the static type, but I don’t think there’s a need to prescribe one naming convention or another... whatever works for you.

**Comment by germanp** [comment]
The actual naming overrides some javascript's standard objects. This can cause that the existing code breaks.

**Comment by germanp** [comment]
You can use something like that to avoid that issue:

`import * as rt from 'runtypes'`

But maybe that affects tree-shaking and bundle size.

**Comment by pelotom** [comment]
> You can use something like that to avoid that issue:
> 
> `import * as rt from 'runtypes'`
> 
> But maybe that affects tree-shaking and bundle size.

This is my standard practice and tree shaking (at least in WebPack) seems to handle it just fine.
